### ISSUE TITLE
Cranelift: support aggregate types ("structs")

### ISSUE THREAD

**Issue by skyne98** [bytecodealliance/wasmtime#1068]
Hello there, I have a slightly trivial question.

How does one represent a structure in Cranelift IR? I know that structures are more-or-less a virtual concept and can be introduced "virtually", by representing parts of them as different objects in memory. However, what if one wants to inter-operate with C library APIs that require passing a structure? As far as I understand, some strict memory layout standard should be followed with correct paddings and organisation. 

Is there any easy way of doing this? Thanks!

**Comment by peterdelevoryas** [comment]
Hey, related to this issue: I'm fine with implementing a struct abstraction in my frontend, but how can I make sure that `create_stack_slot` will have a particular alignment in the stack frame? It seems like right now, alignment is inferred from size? So, there's currently no option for frontends to specify alignment, right?

```
    /// Get the alignment in bytes of this stack slot given the stack pointer alignment.
    pub fn alignment(&self, max_align: StackSize) -> StackSize {
        debug_assert!(max_align.is_power_of_two());
        // We want to find the largest power of two that divides both `self.size` and `max_align`.
        // That is the same as isolating the rightmost bit in `x`.
        let x = self.size | max_align;
        // C.f. Hacker's delight.
        x & x.wrapping_neg()
    }
```

So, for example, if I have a struct with a `i32x4` and an `i64`:

```
struct Data {
    x: i32x4,
    y: i64,
}
```

`size(Data) = 24`, and `align(Data) = 16`.

But, if I do `create_stack_slot(explicit, 24)`, the alignment of the slot will be _8?_ Assuming I'm on like x86, where the stack pointer will be aligned to 16? (Referencing the following test)

    #[test]
    fn alignment() {
        let slot = StackSlotData::new(StackSlotKind::SpillSlot, 8);

        assert_eq!(slot.alignment(4), 4);
        assert_eq!(slot.alignment(8), 8);
        assert_eq!(slot.alignment(16), 8);

        let slot2 = StackSlotData::new(StackSlotKind::ExplicitSlot, 24);

        assert_eq!(slot2.alignment(4), 4);
        assert_eq!(slot2.alignment(8), 8);
        assert_eq!(slot2.alignment(16), 8);
        assert_eq!(slot2.alignment(32), 8);
    }

So, I need to add 8 bytes of padding to the end to make it `create_stack_slot(explicit, 32)`, so that I get an alignment of `16`?

On that note, what is the motivation for defining the `fn alignment` that way? I assume it must be related to how Cranelift is used with wasm?

**Comment by sunfishcode** [comment]
There isn't a great reason for `fn alignment` to be defined that way. It would be better to provide the ability for users to specify an alignment value for each stack slot.

One tricky detail is that Cranelift doesn't yet support dynamically realigning the stack in case someone might use such a mechanism to request an alignment value greater than the platform ABI provides for the stack pointer, however it seems like Cranelift could just fail to compile just cases for now.

**Comment by bjorn3** [comment]
Should we close this as out of scope? We already removed the heap concept used to represent the webassembly linear memory. It should be possible to write an external crate for convenient handling of higher level types which desugars struct accesses into primitive accesses.

**Comment by cfallin** [comment]
Yeah, I think that in the three years (!) since the above discussion, we've come to a clearer consensus about the level of abstraction in CLIF. Namely, we have a view of the world that consists of primitive integer/float types, and loads/stores; and higher-level abstractions can be built from those by the producer. This is explicitly lower-level than LLVM, where one does have a notion of aggregate types and the compiler is responsible for computing their layout. Having only register-sized values makes many things simpler here.

So I'll go ahead and close this as @bjorn3 suggests but anyone please do feel free to leave a note here if there is a compelling argument for this that we've missed.

**Comment by simvux** [comment]
Would it not make sense to support aggregate types in the `cranelift_frontend` crate as it aims to provide an optional convenience on top of `cranelift_codegen`? 

Or would it be out of scope since it requires a bit more logic than just being a builder pattern wrapper

**Comment by cfallin** [comment]
In principle it could be, but I think over time we've converged on `cranelift_frontend` being mostly a wrapper around SSA construction -- it doesn't really have much else in the way of "semantic lowering".

It's possible we could add another abstraction layer -- `cranelift_values` or `cranelift_struct_abi` or something -- that has its own type system that is a superset of core CLIF's, and can handle aggregate types and match the native C ABI for passing them as args and returns. Perhaps part of the reason this doesn't exist yet is that as one moves up the abstraction layers, details start to become application-specific -- for example, a C compiler using Cranelift may want exactly what was just described, but `cg_clif` has its own ABI details that it imports from `rustc` and associated support code and data model.

If you're interested in designing and building such a thing, I think we'd be open to at least helping with the design. It might make sense to build it out-of-tree first, and if it becomes useful for a large number of users then it could eventually move in-tree.

**Comment by fiveseven-lambda** [comment]
In LLVM IR, a function can return a structure:
```llvm
define { i32, i32 } @func() {
    ret { i32, i32 } { i32 1, i32 2 }
}
```
Is there an equivalent way to return a structure in Cranelift?

From what I understand, Cranelift provides ways to compute field addresses using a struct's address and alignment. However, this alone does not seem sufficient to directly return a structure from a function.

**Comment by bjorn3** [comment]
You can have multiple return values. This is equivalent to returning a struct in LLVM IR.

**Comment by fiveseven-lambda** [comment]
@bjorn3 Oh! Thank you.
