### ISSUE TITLE
spidermonkey fails to cross-compile for aarch64, unless --disable-cranelift is passed

### ISSUE THREAD

**Issue by stefson** [bytecodealliance/wasmtime#1083]
this is initially a bug in spidermonkey, but we're running out of ideas what the cause of this might be in the end. So do you think you could give some insight wether it might be caused by cranelift? 

```
how to reproduce: 

download master.zip from https://github.com/mozilla/gecko-dev and unzip, then: 

cd gecko-dev-master/js/src/
autoconf-2.13
mkdir build_OPT.OBJ && cd build_OPT.OBJ

../configure --target=aarch64-unknown-linux-gnu --disable-jemalloc --enable-readline --with-system-nspr --with-system-zlib --disable-optimize --with-intl-api --with-system-icu --disable-debug --enable-ion --disable-tests

make -j12

it fails with this error:

--- stderr
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found, err: true
thread 'main' panicked at 'Unable to generate baldrapi.h bindings: ()', src/libcore/result.rs:1009:5
```

seems as if 32bit headers are pulled into a 64bit process?

**Comment by bnjbvr** [comment]
I think this should be fixed in Spidermonkey, now, since Cranelift is available in Spidermonkey for compiling wasm code (behind a pref, disabled by default, Firefox Nightly only). Please let us know if you run into trouble again! Thanks.

**Comment by stefson** [comment]
if you don't mind to tell what that pref is named, please? :)

**Comment by bnjbvr** [comment]
Sure! I have to be honest and warn that it's a bit messy to enable Cranelift right now, because many wasm features are not supported and thus must be explicitly disabled in the browser, so you need the following:

- javascript.options.wasm_baselinejit set to false (disable wasm baseline compiler)
- javascript.options.wasm_ionjit set to false (disable Ionmonkey for wasm)
- javascript.options.wasm_cranelift set to true
- javascript.options.wasm_reftypes set to false
- javascript.options.shared_memory set to false
- (not sure) javascript.options.wasm_simd set to false

If you find things that are slow / incorrect behavior / cause crashes, please open tickets on our [Bugzilla](https://bugzilla.mozilla.org)!
