### ISSUE TITLE
Better public API for cranelift-frontend than is_pristine() and is_filled()

### ISSUE THREAD

**Issue by sstangl** [bytecodealliance/wasmtime#1101]
In https://github.com/CraneStation/cranelift/pull/862 we added commentary to specify what "pristine" and "filled" meant. Nicolas pointed out that the commentary makes it clear that it could really just be some `EbbState` enum, for example:

```rust
enum EbbState {
  UnChanged,
  Changed,
  ChangedAndTerminated,
}
```

This would help us make better sense of the public interface, where `is_pristine()` and `is_filled()` functions are part of the `FunctionBuilder` public API (used by `cranelift-wasm`), but it isn't clear what those words refer to, so you have to go digging around.

**Comment by bjorn3** [comment]
These methods are no longer public.

**Comment by jameysharp** [comment]
We've had some inquiries showing that people were using `is_pristine` or `is_filled`, so we should keep thinking about whether we should add something like these functions back. They aren't strictly necessary since you can always either track the information yourself while adding instructions, or query the `Layout` and `DataFlowGraph`.

But if we decide we do want helpers for these specific queries, a three-state enum as proposed here is a good idea. I made essentially this change internally in cranelift-frontend as part of #4989, introducing a `BlockStatus` enum.

Still, I think we can safely close this issue.
