### ISSUE TITLE
Missing a way to get access to wasm_instance_t from wasi_instance_t for C-API

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#1220]
For the new wasi.h we can create `own wasi_instance_t* wasi_instance_new`. But there is no away to access the wasm API using the wasi_instance_t handle. E.g. for getting the export table with `wasm_instance_exports`.

Seems like we need an API to get the wasi_instance_t from the wasi_instance_t. To avoid having to replicate all wasm APIs as wasi APIs.

**Comment by peterhuene** [comment]
It's possible if you know the specific export you want from the WASI instance, but it requires using `wasm_importtype_new` to create an import type to pass to `wasi_instance_bind_import` and that's super kludgy.

The reason that `wasi_instance_new` simply doesn't return a `wasm_instance_t*` is that there's currently no way in the C API to get an instance's module and from the module its name so you can resolve imports against a WASI instance manually (one needs to know the "name" of the WASI module that `wasi_instance_new` instantiated).

The `wasi_instance_new` and `wasi_instance_bind_import` functions abstract away the name of the WASI module (or modules) from the instance.  It did it this way for simplicity, but also to punt on how best to support WASI as it evolves standard snapshot to snapshot (the WASI instance might represent a single specific snapshot or potentially multiple WASI for backwards compatibility; the API user doesn't know).

Rather than treating the WASI instance like a normal module instance, I think perhaps having `void wasi_instance_exports(const wasi_instance_t*, own wasm_extern_vec_t*)` would make sense to get at all the exports of the instance for now.

**Comment by rene-fonseca** [comment]
Yes, `wasi_instance_exports` would be fine for now.

**Comment by peterhuene** [comment]
As I mentioned in #1221, the problem with adding a `wasi_instance_exports` is that `wasm_extern_t` won't give any names, so you'd only get a set of functions and their types, without knowing which function is which.

If we were to properly model this, we would need to represent a WASI module with `wasm_module_t` so you could call `wasm_module_exports` to get the symbolic information.

So maybe have `wasm_module_t* wasi_module_new(wasm_store_t*, const char* name)` where name must be a supported WASI version.  From there the usual functions would work.

This is a bunch of work, but it would unify the two APIs (Wasm C API and the WASI extensions) more.

**Comment by plicease** [comment]
> So maybe have `wasm_module_t* wasi_module_new(wasm_store_t*, const char* name)` where name must be a supported WASI version. From there the `wasm_instance_*` functions would work.

It would be great from my perspective to be able to treat wasi as regular module and not have to special case it.

**Comment by bjorn3** [comment]
I believe the wasi implementation now integrates seamlessly with wasmtime\_\*. Does it still make sense to keep this issue open?
