### ISSUE TITLE
Why not publish wasmtime-cli itself?

### ISSUE THREAD

**Issue by clouds56** [bytecodealliance/wasmtime#1361]
So that we can `cargo install wasmtime-cli`

**Comment by tschneidereit** [comment]
`cargo install wasmtime` installs the cli, so that should work as expected.

However, using the installer as described on [wasmtime.dev](https://wasmtime.dev) has advantages, such as not needing to compile, and setting up a directory for a cache which makes uses of the same `.wasm` file much faster after the first compile.

**Comment by alexcrichton** [comment]
@tschneidereit oh actually the embedding API crate took the name `wasmtime`, so `cargo install wasmtime` won't work. I do think though that we should probably publish the CLI itself, so I think we largely just need to update our publication scripts to publish `wasmtime-cli` in addition to the rest of the crates.

**Comment by tschneidereit** [comment]
Oh, hah—serves to show how it's been since I tried this! @clouds56, my apologies for the misinformation.

@alexcrichton that sounds good to me, yes.

**Comment by sunfishcode** [comment]
`cargo install wasmtime-cli` now works, and installs the `wasmtime` command!
