### ISSUE TITLE
there are now two WASI submodules

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasmtime#1427]
As of 6c0c9a46 (#1416), there are two WASI submodules, one at `crates/wasi-common/WASI` and one at `crates/wasi-common/wig/WASI`. The commit message doesn't make it clear which of these is intended. I suspect this is something that got messed up in the squash merge?

**Comment by sunfishcode** [comment]
Sorry for the confusion here. The problem is that `cargo publish` doesn't include `wig/WASI` in the `wasi-common` package, causing it to break when built out of tree. An `include = ` directive in Cargo.toml didn't fix it. Adding a `WASI` symlink fixed it for Mac and Linux but didn't work on Windows. 

Since both `wasi-common` and `wig` need a `WASI` directory, for now, the simplest way to fix it was to give them each their own.

**Comment by pchickey** [comment]
Dang. Well, `wig` is hopefully on its last legs, I expect we'll be able to get rid of it within a month or so. In the meantime, we point to the `witx` path underneath `wig`. If the one under `wasi-common` is expected to eventually be the only remaining, should we point there instead?

And, can we add some sort of CI check that both submodules have the same rev checked out, so that they dont accidentally get out-of-sync?

I'll take both of these tasks.

**Comment by alexcrichton** [comment]
I managed to cook up https://github.com/bytecodealliance/wasmtime/pull/1434 which I think removes the need for two submodules through "weird cargo hacks"

**Comment by pchickey** [comment]
Thank you!
