### ISSUE TITLE
Missing git tag for 0.17, and no github releases since 0.15

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#1841]
Seems like something's off with our release scripts/procedures: we don't have git tags for 0.17, and we don't have [github releases](https://github.com/bytecodealliance/wasmtime/releases) for anything after 0.15.

CC @alexcrichton @sunfishcode

**Comment by alexcrichton** [comment]
I just [pushed a tag for v0.17.0](https://github.com/bytecodealliance/wasmtime/releases/tag/v0.17.0), but we do have a [release for v0.16.0](https://github.com/bytecodealliance/wasmtime/releases/tag/v0.16.0)? Did that perhaps show up since this was opened? FWIW the [release process](https://bytecodealliance.github.io/wasmtime/contributing-release-process.html) does have a tagging step.

**Comment by alexcrichton** [comment]
Hm the [tag failed to build](https://github.com/bytecodealliance/wasmtime/runs/750282286?check_suite_focus=true), though, since CI didn't pass on the commit itself...

**Comment by bjorn3** [comment]
v0.17.0 has a tag but no release. No releases after that are missing.

**Comment by tschneidereit** [comment]
I think it's fine not to have the release for this tag. Ideally we'd not have tagged a rev that didn't build, but I don't think this matters much, given how long ago it was.
