### ISSUE TITLE
Share memory between linked modules

### ISSUE THREAD

**Issue by bubagl** [bytecodealliance/wasmtime#1934]
I've tried to experiment with linking several wasm modules together (https://github.com/bytecodealliance/wasmtime/blob/master/examples/linking.rs). It works but it seems the memory isn't "shared". For instance it is impossible to send a string between modules. Am I missing something? Thanks!

**Comment by bjorn3** [comment]
WASI modules export their memory. They don't import it. This means that every WASI module has it's own memory that it gives access to others to. It never accesses memory of other modules.

**Comment by bubagl** [comment]
> It never accesses memory of other modules.

Is there any way to send data between different modules except "by value"?

**Comment by bjorn3** [comment]
You need to make all modules except for at most one import the memory instead of export. This means that you will have to use `wasm32-unknown-unknown` instead of `wasm32-wasi` and then use I think `-Clink-arg=--import-memory` to tell LLD to import the memory instead of export it.

**Comment by bubagl** [comment]
> have to use `wasm32-unknown-unknown`

but in this case the module wouldn't be able to use any system/wasi call.

**Comment by bubagl** [comment]
Btw, what is the usecase of merging multiple wasms into a single instance?

**Comment by alexcrichton** [comment]
Today it's somewhat difficult to set this up. Wasm modules today can have at most one memory, which means you can't natively, in wasm, copy between memories (since you can only reference at most up to one). This means that there's two ways you can set up modules which "share" a linear memory:

* The host itself can copy between memories. On the host you can reference all the memories you want, but you'd have to implement the boilerplate of marshalling messages between modules. Eventually with interface types it's intended that the runtime can do this for you.

* You can compile all wasm modules to import a memory, and then the host provides a single memory to each module. This is a form of "dynamic linking" in the wasm world, but AFAIK the support is somewhat limited here in toolchains. I believe it's technically possible to get things working but you're sort of on your own in the way of documentation, examples, etc.

I don't think you're currently missing anything about wasm, this is sort of just about how the state of toolchains are today. We're working to improve things with interface types, though, as well as the module linking proposal which will guide toolchains towards wasm modules which are easily linked together.

> Is there any way to send data between different modules except "by value"?

Functions can only pass integers around at this time. With interface types you'll be able to pass richer types. Passing a pointer, however, will only work if the modules reference the same memory or know which memory the pointer is pointing to.

> Btw, what is the usecase of merging multiple wasms into a single instance? Does this feature has any limitations?

Wasmtime doesn't do this and this sounds like more of a toolchain question? There's various reasons you might want to do this but why is this question coming up? Do you have a use case in mind you'd like to game out?

**Comment by bubagl** [comment]
> We're working to improve things with interface types

Interface types are are defined by IDL (WebIDL), correct?

**Comment by alexcrichton** [comment]
A previous iteration of the proposal worked with WebIDL but they are no longer based on WebIDL (although there will be a definition of a translation from WebIDL to interface types). Currently interface types are not implemented in Wasmtime.

**Comment by bubagl** [comment]
> A previous iteration of the proposal worked with WebIDL 

That's interesting! What the new iteration is based on?

**Comment by tschneidereit** [comment]
> That's interesting! What the new iteration is based on?

The most important part is the encoding in the binary and text formats for WebAssembly itself, as described in [the explainer](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md). See also [the section on WebIDL integration](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md#web-idl-integration) in that explainer.

In the explainer, you can see snippets that include extensions to the `wat` text format. I've seen people call this `wit`, and WASI uses an extended form of it, called `witx`. Developer tools will probably use something along these lines to define interfaces, as described by @radu-matei in [a recent blog post](https://radu-matei.com/blog/wasm-api-witx/).

**Comment by bubagl** [comment]
Will wasmtime support "dynamic linking" (https://webassembly.org/docs/dynamic-linking) in the future?

**Comment by alexcrichton** [comment]
Wasmtime should "support" that today actually, in the sense that the dynamic linking as proposed there is purely an embedder construct building on core wasm building blocks. AFAIK C/Emscripten have at least basic support for that style of linking but I don't think that it's super widely used at this time. The [module linking proposal](https://github.com/webassembly/module-linking) may become a new foundation for dynamic linking.

In any case Wasmtime will support dynamic linking of wasm modules, it's mostly just a question of how exactly that will look like in the ecosystem.

**Comment by bubagl** [comment]
> Wasmtime should "support" that today actually

could you point out some example of dynamic linking. I don't see `dlopen` implemented by WT.

**Comment by alexcrichton** [comment]
I don't currently know of any examples of dlopen and/or that scheme of dynamic linking. I believe it's mostly just a description of how it *could* work rather than a working system. The purpose of that explanation, however, is how it can be built on the MVP of wasm and doesn't need runtime support, so for that scheme of dynamic linking you won't find it in Wasmtime.

**Comment by willygroup** [comment]
Thanks for the reply.
I managed to import the same memory for both modules and this looks "almost" to work if I don't mess too much with the memory allocation :D 
There is no way to tell a module to use the allocator from another module?
Like this is not very useful linking modules for my project :disappointed:

**Comment by bjorn3** [comment]
> There is no way to tell a module to use the allocator from another module?

Maybe if you only link a single wasm module against the allocator and then let the other link against the allocator functions of the first? As for how to achieve this, I have no idea.

**Comment by davxy** [comment]
Hi there. I'm interested as well :)

Preamble: 
- I have a two modules, A and B, and I like to use B as a shared library.
- A is tiny and contains only the code that implements the application business logic.
- B is huge and contains all the std library functions and utilities

In particular, I'm trying to:
- 1. share the memory between two modules => DONE
- 2. call a function of module A from module B => DONE
- 3. prevent A from statically link the std library stuff, eg. allocator code => NOT DONE (how we can do that?)
- 4. prevent that an allocation in module A clash with an allocation in module B => NOT DOVE (I suppose that can be resolved by the point 3 by letting B using the allocator in A.

Any ideas?

Thanks for you awesome work, David

**Comment by bjorn3** [comment]
It seems that there is a tool convention for dynamic libraries<sup>[1]</sup>, but it is a work in progress and requires either using emscripten, which only runs on the web, or parsing a "dylink" section when loading to determine which dynamic libraries to load and then some additional code to actually link them. [2] gives some more information on how to make it work. At the time of writing of that article there were a couple of bugs in LLVM and lld. I don't know if they are all fixed yet.

[1]: https://github.com/WebAssembly/tool-conventions/blob/main/DynamicLinking.md
[2]: https://iandouglasscott.com/2019/07/18/experimenting-with-webassembly-dynamic-linking-with-clang/

**Comment by alexcrichton** [comment]
I'm going to close this since this issue is quite old at this point and in general the problems here are toolchain-related rather than Wasmtime related.
