### ISSUE TITLE
Use interface for calls between modules

### ISSUE THREAD

**Issue by bubagl** [bytecodealliance/wasmtime#1979]
Is it possible to use interface types when making calls between "linked modules" (https://bytecodealliance.github.io/wasmtime/examples-rust-linking.html)? I suspect the answer is negative because modules have isolated memory.

**Comment by tschneidereit** [comment]
It's not yet possible, because we don't yet have a real implementation of Interface Types, and the spec itself isn't stable yet.

> I suspect the answer is negative because modules have isolated memory.

Once we do support Interface Types, they will work for this use case: Interface Types are specifically intended to enable passing structured data between modules (or from modules to the host and vice versa) without giving up on memory isolation.

**Comment by alexcrichton** [comment]
I'm going to close this since this is pretty old and the old interface types proposal, now the component model, is in the progress of being implemented in Wasmtime.
