### ISSUE TITLE
Intermittent CI failure in new x64 backend

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#2109]
We have temporarily disabled the new x64 backend's CI tests (#2100) because it would intermittently fail these tests with a crash. We need to resolve the underlying issue (perhaps a codegen bug) and re-enable the tests.

**Comment by cfallin** [comment]
cc @julian-seward1 @bnjbvr

**Comment by bnjbvr** [comment]
I don't have strong evidence, but I think this has been fixed by https://github.com/bytecodealliance/wasmtime/commit/3849dc18b1bf3560c43950f049fe553034c424b2.

See https://github.com/bytecodealliance/wasmtime/commit/3849dc18b1bf3560c43950f049fe553034c424b2#diff-234d9b09197fd3d4bc69bf1a2ca4f2f8L2410. Before the PR, when emitting a constant `null` for a reference type, we wouldn't match the `is_int`, so a floating-point xorps/xorpd would be used to generate the register. According to the result of regalloc, this could result in incorrect code in the best case, uninitialized registers in the worst case. The above patch is a likely fix since the issue was intermittent, and matches this behavior of randomness, and crashes happened around reference type tests (I remember seeing double frees, etc.).

I'll close the issue now; if the intermittent failure happens again, I'm happy to look into it a bit more.
