### ISSUE TITLE
WASI on Mobile

### ISSUE THREAD

**Issue by nxtexe** [bytecodealliance/wasmtime#2342]
What about a iOS/Android WASI engine? Are there any discussions about such a possibility? Also possibly embedded systems?

**Comment by alexcrichton** [comment]
Currently [Wasmtime's supported platforms](https://docs.wasmtime.dev/stability-platform-support.html) do not include iOS or Android, but there is no fundamental reason that they aren't supported beyond "someone needs to do the porting and testing work". 

Otherwise this is quite old so I'm going to close this issue. If there's interest in adding support for a specific target I think it'd be best for a fresh issue categorized as a feature request to add a target.
