### ISSUE TITLE
wasmtime doesn't support fibers on platform s390x

### ISSUE THREAD

**Issue by e-desouza** [bytecodealliance/wasmtime#2825]
I noticed lack of s390x support from the docs and as expected, it does fail on RHEL 8 on s390x.

`thread 'main' panicked at 'wasmtime doesn't support fibers on platform: s390x-nknown-linux-gnu', /home/linux1/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/wasmtime-fiber-0.24.0/build.rs:17:9`

I can provide s390x machines so what is the best way integrate into the CI/CD pipeline? Implementing the JIT will be non-trivial but we could start with just plain old interpreted mode (if one exists).

**Comment by cfallin** [comment]
Greetings, @e-desouza!

Indeed, as you note, fibers support is a somewhat minor issue on a new CPU architecture compared to the main hurdle: adding JIT-compiler support. (Wasmtime doesn't yet have an interpreter mode but it may in the future.)

Regarding the Cranelift-based JIT: @uweigand has actually been working on s390x support for a while now; my understanding is that there is a backend that works but it is still in progress and has not yet been made public / merged. CI is an issue: @uweigand also offered access to s390x machines via IBM but GitHub's CI runner (used to run CI on one's own machines) is a .NET program, apparently, and .NET itself has not been ported to s390x. In principle we could merge something without CI and support it on a "it will keep compiling" best-effort basis, though.

Anyway -- @uweigand, do you have any recent updates on this?

**Comment by uweigand** [comment]
Hi @e-desouza, I'd be interested to understand your use case for wasmtime on Z (feel free to contact me offline).

Indeed I do have a working s390x back-end (which is currently broken due to the unwinder rewrite -- @cfallin, I'll follow up on that with you separately).  While I've been a bit sidetracked with other projects recently, I hope we can get this merged in the medium term to at least benefit from ongoing compile testing.  Ideally, we'd also get the GitHub CI runner going (actually, porting .NET is one of those projects I've been spending my time on recently :-)), but that'll still take some time.
