### ISSUE TITLE
Cranelift: bint produces different results on x64 and aarch64

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#3003]
Hey,

While working on #2978, i found that we are lowering constants inconsistently between backends. x64 always lowers as -1 (i.e. all bits 1) while aarch64 lowers as 1.

I don't know which one is correct, but they should agree with each other. According to [this comment](https://github.com/bytecodealliance/wasmtime/blob/b506bc30b1c8692995e3297fcf1a5d498d4d36d6/cranelift/codegen/src/isa/x64/lower.rs#L3281) I think the behavior on x64 is wrong.

It looks like [cg_clif depends on this behavior](https://github.com/bjorn3/rustc_codegen_cranelift/blob/75eff64977ff149ead73bc0077bac5872d599aa2/src/intrinsics/mod.rs#L293).

### `.clif` Test Case

```
test run
target aarch64
target x86_64 machinst

function %bint_b8_i16() -> i16 {
block0:
  v0 = bconst.b8 true
  v1 = bint.i16 v0
  return v1
}
; Passes on x86, fails on aarch64
; run: %bint_b8_i16() == 0xFF

; Passes on aarch64, fails on x86
; run: %bint_b8_i16() == 1


function %bint_b16_i16() -> i16 {
block0:
  v0 = bconst.b16 true
  v1 = bint.i16 v0
  return v1
}
; Passes on x86, fails on aarch64
; run: %bint_b16_i16() == 0xFFFF

; Passes on aarch64, fails on x86
; run: %bint_b16_i16() == 1
```

### Steps to Reproduce

Run the above test

### Expected Results

The aarch64 and x64 backends should produce identical results

### Actual Results

Bools are lowered as either 1 or -1 depending on the backend.

### Versions and Environment

Cranelift version or commit: current main branch
Operating system: Windows 10
Architecture: x64 / aarch64

**Comment by bjorn3** [comment]
-1 is the expected behavior for bmask I think, not for bint.

**Comment by akirilov-arm** [comment]
The `bint` documentation [states](https://docs.rs/cranelift-codegen/0.75.0/cranelift_codegen/ir/trait.InstBuilder.html#method.bint) that either 0 or 1 is the expected result. As for `bconst`, both backends seem to behave identically.

**Comment by cfallin** [comment]
Thanks for finding this!

I did a bit of archaeology just now to try to work out what's going on here, as I recalled we had had some discussions about this already. It turns out that we [have](https://github.com/bytecodealliance/wasmtime/pull/2310#pullrequestreview-519133477), also #2058.

The `bconst` is indeed correct, as per above -- it generates all-ones into the register (this is so that it can be used as a mask). The issue is that I think the `bint` implementation on x64 does not properly mask this down to 0 or 1. It appears that I had added the masking in aarch64 when I made the change in #2058 above but the x64 backend wasn't updated at the same time. I'll do a quick PR to rectify this!
