### ISSUE TITLE
Automatically deploy new tagged versions to PyPI 

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#312]
We should switch to automatically deploying the Python extension whenever we bump the Wasmtime version number, based on the `whl` packages our CI builds.

/cc @yurydelendik

**Comment by luizirber** [comment]
Hi, I recently opened two PRs (#627 and #648) that touch the Python wheel generation, and since now the generated wheels have the right names (and version) I can look into using https://github.com/pypa/gh-action-pypi-publish to publish the wheels to PyPI.

Should I make a new PR?

I obviously don't have permissions to manage the repo secret here in GitHub nor create the PyPI token for upload, so someone with access to those would need to fill it in.

**Comment by alexcrichton** [comment]
That'd be awesome if you could help us tackle this @luizirber, thanks!

If you want to test out on a local copy of the repo and let us know what secrets to configure, we can do that and then merge a PR!

**Comment by OrangeTux** [comment]
@luizirber Are you still working on this? Is there a way I can help?

**Comment by luizirber** [comment]
@OrangeTux feel free to take this one, I didn't do anything other than ask =]

**Comment by OrangeTux** [comment]
@luizirber Cool, I'll take a look at the issue than.

**Comment by OrangeTux** [comment]
I'm not sure if something is wrong with the workflow. The workflow for 0.9.0 release [has failed](https://github.com/bytecodealliance/wasmtime/runs/382815781), although there are some [files uploaded to pypi](https://pypi.org/simple/wasmtime/)

**Comment by alexcrichton** [comment]
@OrangeTux mind helping us to fix this? Some debugging looks like our usage of [`packages_dir`](https://github.com/bytecodealliance/wasmtime/blob/815576edc5ab00da8c6b67916bf7e9f8af1504d2/.github/workflows/main.yml#L503) isn't supported by the [v1.0.0a0 tag](https://github.com/pypa/gh-action-pypi-publish/blob/v1.0.0a0/action.yml), but it is [supported on master](https://github.com/pypa/gh-action-pypi-publish/blob/master/action.yml). I think we may have a duplicate directory called `dist` which caused the build to not fail, but there was probably some stray files in `dist` which cause the upload to fail. I suspect that if we fixed the directory stuff the publication would finish?

We can probably pin to a specific revision of the action on the master branch and get this working?

**Comment by OrangeTux** [comment]
Sure, I am happy to help. Although it probably needs to wait till it is weekend.

**Comment by OrangeTux** [comment]
To me it seems that we've 2 different issues:

1) The first issue is the one you described: the `master` version of the `gh-action-pypi-publish@v1.0.0a0` is not supported.

2) The job for uploading the Python wheels to Pypi has run at least twice for `v0.9.0`. The first time was at [the build](https://github.com/bytecodealliance/wasmtime/runs/382653920?check_suite_focus=true) of commit 5427a8e05105d1e19eec6e06c2c08426ee4135e9. 
You can see that the job `Publish Python wheels on Pypi` has ran. It uploaded 9 wheel files to Pypi before the `gh-action-pypi-publish` encountered an unknown file format and failed. It probably encountered this file because of issue 1: the action is not respecting the `packages_dir`. 
Than this job `Publish Python wheels on Pypi` [is ran again](https://github.com/bytecodealliance/wasmtime/runs/382815781) for commit https://github.com/bytecodealliance/wasmtime/commit/632e5256a7d6d1a2a086d9f07c028e281c2a5024. Now the job fails because you cannot republish packages to Pypi with the same name. 
The question is why this job has run twice for the same tag? Did someone retagged v0.9.0?

**Comment by OrangeTux** [comment]
I [opened an issue](https://github.com/pypa/gh-action-pypi-publish/issues/24) and asked if the author can create a new release.

**Comment by alexcrichton** [comment]
According to [this documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses) it looks like we don't have to necessarily wait for a release, we can pin to a specific revision? We can likely pin to whatever `master` is right now and update it to a release next time that happens

As for the double-tag I'm not sure, but it's something we can keep an eye out for in the future!
