### ISSUE TITLE
Add fuel units to `consumed_fuel` into a store

### ISSUE THREAD

**Issue by willygroup** [bytecodealliance/wasmtime#3315]
Is there a way to add some fuel units to the consumed fuel?

I would like "to charge" the calls to my host functions.

And why a function that uses an host function to store a Vec<u8> consumes about 10-20 times fuel that a function that uses another host function to load the same data

Thanks a lot for your work!

**Comment by alexcrichton** [comment]
By units, do you mean a meaning to the number used to inject fuel? If so that doesn't really have any units per-se and the exact calculation of what fuel is is somewhat fuzzy. It somewhat corresponds to wasm instructions, but not always precisely so.

Fuel is not consumed by host functions, though, other than the `call` instruction used to enter host code. Different host code should always look like it consumes the same amount of fuel. Can you describe the situation in which you're seeing two host functions consume different  amounts of fuel?

**Comment by bjorn3** [comment]
I think @willygroup wants different host functions to consume specific amounts of fuel determined by said host function.

**Comment by willygroup** [comment]
@alexcrichton yes, I was thinking just such a thing.

**Comment by willygroup** [comment]
> And why a function that uses an host function to store a Vec consumes about 10-20 times fuel that a function that uses another host function to load the same data

Any hints for this?
To test it, I've written a small wasm with 3 methods:
 - store(data_addr: i32, data_size: i32)
    - the data is stored on the memory from the host before the `store` call
 - load() -> i64
    - return an i64 as combination of i32 address ant i32 size of the return data slice

that use 2 host function: 
 - store_data(key: &str, data: Vec<u8>)
 - load_data(key: &str) -> Vec<u8>
 Vec<u8> are passed as memory address and memory size

The fuel consumed by these methods is the following:
 - store 	data: 100bytes  ### FUEL CONSUMED: 6_995
 - load	data: 100bytes  ### FUEL CONSUMED: 18_971
 - store 	data: 50KB		### FUEL CONSUMED: 855_692
 - load 	data: 50KB      ### FUEL CONSUMED: 6_589_590
 - store	data: 100KB     ### FUEL CONSUMED: 1_705_726
 - load	data: 100KB     ### FUEL CONSUMED: 13_726_190

Thanks a lot!
