### ISSUE TITLE
Remove `cranelift-codegen`'s `build.rs`

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#3531]
We should check in all generated code, since it doesn't change based on any user of `cranelift-codegen`'s input or system or anything like that, and have a script that we can re-run as needed to regenerate these files. This will speed up compile times and remove `cargo build` time dependencies.

See also this thread https://github.com/bytecodealliance/wasmtime/pull/3506#discussion_r743045020

**Comment by cfallin** [comment]
As noted in #3540, possibly a good way to go about this would be to maintain a small `build.rs` that just does a check for stale sources by comparing the meta-sources against a manifest, as #3534 does for ISLE. I think we should try to protect against this otherwise somewhat probable silent failure for new contributors; hopefully a `build.rs` that just uses `sha2` and nothing else is relatively fast to compile :-)

**Comment by alexcrichton** [comment]
Given the experience from https://github.com/bytecodealliance/wasmtime/issues/4066 it seems we're pretty unlikely to reverse direction at this point, so I'm going to close.
