### ISSUE TITLE
Could not download Wasmtime version 'dev'

### ISSUE THREAD

**Issue by marmeladema** [bytecodealliance/wasmtime#3851]
The standard installation method is now failing:
```
$ curl https://wasmtime.dev/install.sh -sSf | bash
  Installing latest version of Wasmtime (dev)
    Checking for existing Wasmtime installation
    Fetching archive for Linux, version dev
https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz 
curl: (22) The requested URL returned error: 404

Error: Could not download Wasmtime version 'dev'. See https://github.com/bytecodealliance/wasmtime/releases for a list of available releases
```

**Comment by alexcrichton** [comment]
Thanks for the report, but this will periodically happen while CI is rebuilding the `dev` release (the upload is in the process of being built but it isn't finished). For that it's best to probably use released versions if you can, and it would likely also be prudent for us to change `install.sh` to using latest-stable instead of the `dev` release.

**Comment by marmeladema** [comment]
I personally never intended to install the dev version. I am just using the officially documented way of installing wasmtime as described in the readme.
Is there a way to install the latest stable release already?

**Comment by alexcrichton** [comment]
Ok I think I've fixed this in https://github.com/bytecodealliance/wasmtime.dev/pull/11 where `dev` is no longer the hardcoded release.

**Comment by marmeladema** [comment]
Thanks! It worked this time but I think it still downloaded the dev version.

**Comment by alexcrichton** [comment]
Ah looks like the github-pages deploy failed but I reran it and it looks to be updated now
