### ISSUE TITLE
Does wasmtime c api currently support compiling to Android/iOS platform?

### ISSUE THREAD

**Issue by LukiYLS** [bytecodealliance/wasmtime#3867]

**Comment by alexcrichton** [comment]
Wasmtime's platform support is [documented here](https://docs.wasmtime.dev/stability-platform-support.html). Android is not tested on CI and guaranteed to work at this time, but Wasmtime may compile for these platforms and we'll take PRs to fix issues if they arise.

**Comment by martindevans** [comment]
As far as I can see the linked page does not mention "Android" anywhere, has it been removed?

I was going to up a new issue, but this one seems appropriate to ask in: Would it be possible for Android C-API binaries to be included in the monthly releases? It [looks like](https://github.com/bytecodealliance/wasmtime/blob/83ac69ca840dc20ecda1892d417031bad90060cf/.github/workflows/main.yml#LL296C50-L296C71) there's already some support for building and testing android binaries, so perhaps it's just a matter of including them in the release list?

**Comment by alexcrichton** [comment]
It's not been removed, Android was never present since it's only ever been best-effort so far. That being said the better documentation nowadays is [here](https://docs.wasmtime.dev/stability-tiers.html) (which still doesn't mention Android) and it would be a good fit for Tier 3 support (since we'd build it and not run tests).

If you're up for it I think it'd be reasonable to review a PR adding support for Android binary releases which updates the tier support documentation as well with an Android target.

**Comment by alexcrichton** [comment]
Ok sounds good, and thanks!

To assist a bit, the release build matrix is [here](https://github.com/bytecodealliance/wasmtime/blob/72b641d5dada4084b5ec839968ffd1655d64be1b/.github/workflows/main.yml#L681-L702) and in theory it's "simply" adding another line there, but my guess is that some other tooling like `cargo ndk` will need to be installed similar to [this](https://github.com/bytecodealliance/wasmtime/blob/72b641d5dada4084b5ec839968ffd1655d64be1b/.github/workflows/main.yml#L298-L305C1)
