### ISSUE TITLE
Example of how to embed

### ISSUE THREAD

**Issue by VioletasTheThird** [bytecodealliance/wasmtime#39]
I believe there should be an example somewhere in the repo, demonstrating how to embed the runtime into people's own applications, along with examples of exposing functions, and any other possible runtime manipulations (assuming all of this is possible in the project's current state)

**Comment by sunfishcode** [comment]
Ah, reading this again, I see that this issue is for Wasmtime, not Cranelift itself. So disregard my previous message :-}.

Currently, the best example we have is `src/wasmtime.rs` in the main tree, which is the command-line driver for the libraries. It shows how to load a wasm module, instantiate it, and invoke functions on it.

I agree that we need more examples :-) For now, if there's anything you have questions about, feel free to ask!

**Comment by maxmcd** [comment]
A few questions in the same vein. I have a messy working example using wasmtime. (The code is [here](https://github.com/maxmcd/wasm-servers/tree/master/runtime/src))

I've taken most of my inspiration from the spectests. Is the expectation that external functions will be defined on a separate module and then called between modules? In getting a simple rust wasm example working with a print statement I have most of the code from `src/wasmtime.rs` and then I define a separate module with the external function I want to call: https://github.com/maxmcd/wasm-servers/blob/master/runtime/src/resolver.rs#L154-L197

In order to share memory between modules I effectively copy and paste `InstancePlus::new` and add this line: https://github.com/maxmcd/wasm-servers/blob/master/runtime/src/instance_plus_plus.rs#L39-L41

Seems a little awkward at the moment, but I'm sure it can be cleaned up. No pressure to go through my code, but more generally would be great to hear your thoughts on what the structure of a simple foreign function example would look like.

**Comment by sunfishcode** [comment]
Yes, if you want functions defined by the host, the main expected way to do that is to put them in their own module, similar to the spectest module. Hopefully we'll have more examples of that soon. That's not the only way it can be done, but it does simplify some things, such a code caching (which isn't implemented yet, but which is anticipated in the current design) because we can then just cache a whole module as a unit.

The APIs for doing this aren't very streamlined yet, but I'm working on it. One thing I'm specifically working on right now is extracting out parts of the WastContext functionality from lib/wast for loading multiple modules and making their exports automatically available for subsequent imports.

Modifying the module manually, to add a memory import, is somewhat awkward. Ideally, the wasm module itself should have an import, so that the VM doesn't need to inject it itself.

That said, there is a broader issue where you want to have module A use functions from module B, and then those functions need to access memory from module A. This will likely get solved for real when [host-bindings](https://github.com/WebAssembly/host-bindings/blob/master/proposals/host-bindings/Overview.md) arrives, allowing us to pass slices of memory around as parameters. Until then, we need a  temporary solution, and we're still experimenting with various options.

**Comment by maxmcd** [comment]
Would the expectation be that the cache is portable? Even some kind of binary format that would represent a compiled `.wasm`? 

Thanks for the clarifications. Those WastContext changes sound great.

**Comment by maxmcd** [comment]
One more question: the `wasmtime_call_trampoline` passes a `VMContext`. If a user of the wasmtime lib wanted to pass more context to the function calls is the expectation that one would write their own call trampoline? 

As a simple example let's say I wanted to mock out environment variables, and hold them in a hashmap within the runtime. I write my own InstancePlus::invoke and sort out my own call trampoline?

I guess it makes a lot of sense to just implement a custom InstancePlus-type struct with the desired functionality?

**Comment by sunfishcode** [comment]
> Would the expectation be that the cache is portable? Even some kind of binary format that would represent a compiled .wasm?

I haven't thought much about the format of the cache yet, but at the very least, it'll contain machine code, so it won't be portable between hardware architectures, nor between operating systems with different calling conventions (eg. Windows vs. everything else on x86-64).

One possible direction here is to build out lib/obj and src/wasm2obj.rs in the tree, which is an early experiment writing out a native object file containing compiled wasm code, so that we can use them for caching too.

> One more question: the wasmtime_call_trampoline passes a VMContext. If a user of the wasmtime lib wanted to pass more context to the function calls is the expectation that one would write their own call trampoline?

The functions called by `wasm_call_trampoline` handle calling from dynamically constructed calls into compiled wasm code. Wasm-to-wasm calls don't go through `wasmtime_call_trampoline`. So if you want extra arguments passed to wasm functions in general, the trampoline logic won't be sufficient.

I'm expecting to introduce some "global" runtime state soon, where each `Instance` will have a pointer to this state. We need this to properly implement the shared signature table, and a shared code registry, and other things, and then one option is to adopt an idea @lachlansneff suggested to me a while ago, to add a way for embedders to add their own data to this. That way, you could add your data, and get to it when given a `VMContext` pointer. Does that sound like it would work?

**Comment by maxmcd** [comment]
Very much a fan of per-instance state. Looks good to me.

I'm trying to update my code with the new changes. `(&mut *vmctx).instance_contents()` (formerly `instance`) is now private. How should one access shared memory with a vmctx? Is it up to me to make that available in `host_state`?

**Comment by maxmcd** [comment]
Got the new structure working. Really helps clean things up. 

For memory access I do this:
```rust
let mut instance = instantiate(compiler, &data, &mut namespace).map_err(|e| e.to_string())?;

let definition = match instance.lookup("mem") {
    Some(wasmtime_runtime::Export::Memory {
        definition,
        memory: _memory,
        vmctx: _vmctx,
    }) => definition,
    Some(_) => panic!("exported item is not a linear memory",),
    None => panic!("no export "),
};

let go_instance = &mut namespace.instances[go_index];
let host_state = go_instance
    .host_state()
    .downcast_mut::<resolver::SharedState>()
    .expect("did not downcase a SharedState");
host_state.definition = Some(definition);
```
Grab the memory from the instantiated instance and add it to the host_state. I end up having to add `pub` to `namespace.instances` to allow access after the instance has been added to the namespace. My Rust knowledge might be failing me here, maybe I can just hold a reference to the ShareState. Any thoughts on this structure, or how to accomplish without modifying wasmtime?

**Comment by buckle2000** [comment]
Still, how do I expose `func` in rust to wasm module?

**Comment by sunfishcode** [comment]
Assuming `func` is exported, you can call `lookup` to look it up by name. That gives you `Export`, which assuming its an `Export::Function`, gives you the function address which you can cast to a rust function reference, and the vmctx argument to pass to it. Alternatively, you an use the `invoke` function to do a lot of this for you, though it'll use a trampoline rather than a direct call.

That's what's currently possible. In the future, I'm hoping we'll have more ergonomic utilities to wrap this functionality.

**Comment by sunfishcode** [comment]
> Got the new structure working. Really helps clean things up.

Cool!

> For memory access I do this:
> 
> ```rust
> let mut instance = instantiate(compiler, &data, &mut namespace).map_err(|e| e.to_string())?;
> 
> let definition = match instance.lookup("mem") {
>     Some(wasmtime_runtime::Export::Memory {
>         definition,
>         memory: _memory,
>         vmctx: _vmctx,
>     }) => definition,
>     Some(_) => panic!("exported item is not a linear memory",),
>     None => panic!("no export "),
> };
> 
> let go_instance = &mut namespace.instances[go_index];
> let host_state = go_instance
>     .host_state()
>     .downcast_mut::<resolver::SharedState>()
>     .expect("did not downcase a SharedState");
> host_state.definition = Some(definition);
> ```
> 
> Grab the memory from the instantiated instance and add it to the host_state. I end up having to add `pub` to `namespace.instances` to allow access after the instance has been added to the namespace. My Rust knowledge might be failing me here, maybe I can just hold a reference to the ShareState. Any thoughts on this structure, or how to accomplish without modifying wasmtime?

Hmm, there should probably be an accessor that returns the instance for a given `InstanceIndex`, which if I understand correctly would do what you need here.

**Comment by buckle2000** [comment]
Sorry, I mean the other way around. How do I expose rust function to webassembly module?

I already know how, but the code itself is confusing.

**Comment by maxmcd** [comment]
I don't have a working rust runtime with wasmtime at the moment, but the pieces are here: https://github.com/maxmcd/wasabi/blob/7987e09e4/wasabi/src/rust.rs

That ran this: https://github.com/maxmcd/wasabi/blob/7987e09e4/programs/rust-basic/src/lib.rs

I think rust .wasm bins were working here: https://github.com/maxmcd/wasabi/blob/711fdb7daae3b97ea00d4de58d027af328a93317/runtime/src/main.rs but there's a lot more going on in that version. 

Happy to work on a minimal example to add to this repo if that's desirable.

**Comment by alexcrichton** [comment]
The `wasmtime` API crate has progressed quite a bit since this issue was first created, and there's a few small examples in `crates/api/examples`, so I'm going to close this.

**Comment by eminence** [comment]
There's also a good introduction here:  https://github.com/bytecodealliance/wasmtime/blob/master/docs/embed-rust.md

**Comment by slipher** [comment]
I found the existing examples lacking, as there was no example of host functions that read/write sequences of data in the WASM memory. So I created https://github.com/slipher/wasmtime-bad-example.

You may proceed to tell me how I am holding it wrong.

**Comment by yurydelendik** [comment]
@slipher I think main issue above is that you are trying to mix non-API/internal stuff with public wasmtime API -- it is over-complicated and hard to see what is going wrong there.

The following code is remix of the provided [memory](https://github.com/bytecodealliance/wasmtime/blob/master/crates/api/examples/memory.rs) and [hello](https://github.com/bytecodealliance/wasmtime/blob/master/crates/api/examples/hello.rs) examples:

```
use anyhow::{bail, ensure, Context as _, Error};
use wasmtime::*;
use std::rc::Rc;
use std::cell::RefCell;
use std::fs::read;

struct LogCallback {
  memory: Rc<RefCell<Option<Memory>>>,
}

impl Callable for LogCallback {
    fn call(&self, _params: &[Val], _results: &mut [Val]) -> Result<(), Trap> {
        println!("Calling back...");
        let ptr = _params[0].unwrap_i32() as usize;
        let len = _params[1].unwrap_i32() as usize;
        unsafe {
          let memory = self.memory.borrow();
          let data = &memory.as_ref().unwrap().data_unchecked()[ptr..ptr + len];
          println!("> print: {}", std::str::from_utf8_unchecked(data));
        }
        Ok(())
    }
}

fn main() -> Result<(), Error> {
    // Initialize.
    println!("Initializing...");
    let store = Store::default();

    // Load binary.
    println!("Loading binary...");
    let wasm = read("helloworld.wasm")?;

    // Compile.
    println!("Compiling module...");
    let module = Module::new(&store, &wasm).context("> Error compiling module!")?;

    if module.imports().len() != 1 || module.imports()[0].name() != "WasmLog" {
      bail!("Not a WasmLog");
    }

    let memory: Rc<RefCell<Option<Memory>>> = Rc::new(RefCell::new(None));

    println!("Creating callback...");
    let log_type = FuncType::new(Box::new([ValType::I32, ValType::I32]), Box::new([]));
    let log_func = Func::new(&store, log_type, Rc::new(LogCallback { memory: memory.clone() }));

    // Instantiate.
    println!("Instantiating module...");
    let instance = Instance::new(&module, &[log_func.into()]).context("> Error instantiating module!")?;

    println!("Find and set memory export...");
    *memory.borrow_mut() = Some(instance.get_export("memory").context("memory export")?.memory().context("memory")?.clone());

    println!("Find and call helloworld export...");
    let run_func = instance.get_export("helloworld").context("helloworld export")?.func().context("helloworld func")?;
    run_func.call(&[])?;

    // Shut down.
    println!("Shutting down...");
    drop(store);

    println!("Done.");
    Ok(())
}
```

**Comment by slipher** [comment]
I couldn't find `instance.get_export` in the docs. Is it a new, not yet published API or something?

**Comment by yurydelendik** [comment]
> I couldn't find instance.get_export in the docs. Is it a new, not yet published API or something?

Right, it is past 0.9.0 [change](https://github.com/bytecodealliance/wasmtime/commit/e5afdd2edecfd39a0989cf7cda634e242eeb4591#diff-bd92fb85af37056841d90f0e00636d99R162). It is renamed `find_export_by_name`.
