### ISSUE TITLE
cranelift: If it is ok to write a new backend without the isle???

### ISSUE THREAD

**Issue by yuyang-ok** [bytecodealliance/wasmtime#3919]
isle looks quit  complicated.
especially for someone not familiar.

**Comment by cfallin** [comment]
Hi @yuyang-ok -- we're trying to move all backends over to the ISLE DSL, because it enables us to do a lot of useful things. So, we probably wouldn't want to accept a new backend written in handwritten code.

I'm sorry to hear that you're having difficulties though! Anecdotally, we've found that things usually end up in a simpler place -- moving handwritten code to the DSL tends to shrink it by a factor of 2 to 5, and we've found several bugs because it's easier to see what is happening -- but I can understand that the task of writing a whole new backend in a new language could seem daunting.

It's probably useful to think about relative complexities too. We have quite a lot of subtle rules that the handwritten backends have to follow. It's very easy to introduce a bug by missing something, and we've had a few bugs that took weeks to chase down. ISLE pushes some of the thinking upfront, like most statically-typed languages do -- but by doing so, things tend to work once they are written. A lot of this comes out of experience with the alternative; the advantages become more apparent once you've spent time doing things the other way. We wouldn't have wanted to move to ISLE if it had meant that the job of writing a new backend would be more difficult overall.

If there is something that we can do to help, please let us know. At some point it might be good for us to write a tutorial on how to build a new backend from scratch; it's just that no one has had the time to do that yet.

**Comment by yuyang-ok** [comment]
ok,thanks.
