### ISSUE TITLE
Examples for wasm2obj

### ISSUE THREAD

**Issue by jwasinger** [bytecodealliance/wasmtime#40]
I'm trying to get `wasm2obj` working using this wat:

```
(module
  (func $main
    ;; locals
    (local $a i32)

    ;; init
    (set_local $a (i32.const 128))

  )
  (start $main)
)
```

Then:
```
> wat2wasm example.wat -o example.wasm
> wasm2obj example.wasm -o output

error: Undeclared symbolic reference to: wasm_function[0]
```

Could a working example for `wasm2obj` be posted?

**Comment by sunfishcode** [comment]
We haven't had much time for wasm2obj lately because we've been focusing on the runtime, ABI, and jit support in wasmtime. It looks like things aren't quite working right now, unfortunately. I hope to have time to revisit wasm2obj soon though, as it's an important piece of the bigger picture we're building.

**Comment by yurydelendik** [comment]
Looks like changes in faerie lib require declare along with define (at least for me on macos). Trying to fix it at #46

**Comment by yurydelendik** [comment]
Probably fixed in #50 -- the issue can be closed

**Comment by bjorn3** [comment]
Wasm2obj has been deleted in favor of `wasmtime compile`, so this can be closed I think.

**Comment by alexcrichton** [comment]
Indeed
