### ISSUE TITLE
Timeout during spec interpreter execution while fuzzing

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#4059]
We hit a fuzz bug just now where the spec interpreter is timing out the fuzz test case when wasmtime looks to execute the wasm in under a second, so I'm opening this to track investigation into the spec interpreter to see if there's perhaps some performance wins to gain there.

* [wasm](https://github.com/bytecodealliance/wasmtime/files/8524996/testcase0.wasm.gz)
* [fuzz input (gzipped)](https://github.com/bytecodealliance/wasmtime/files/8524997/input.gz)

cc @conrad-watt

**Comment by conrad-watt** [comment]
Ah, interesting. The formal model's implementations of `reinterpret` and `popcnt` are particularly inefficient (still a constant factor only), and it looks like this test calls a whole bunch of them. I'll dig into this on my side, but do you see a big difference in the (forked) spec interpreter's runtime locally when providing/not providing the `-isa` flag?

**Comment by alexcrichton** [comment]
Ah sorry I'm not super familiar with running the interpreter outside the fuzzer itself, can you clarify what you mean by the `-isa` flag?

**Comment by conrad-watt** [comment]
Ah sorry, if it's any trouble, I can look myself later (not at my workstation right now).

When running the spec interpreter from the command line, the invocation normally looks like

`./bin-name -i file-name`

this runs the reference interpreter (more or less) unchanged from the main repository

if you instead run

`./bin-name -isa -i file-name`

it runs using my formal model

if it runs much slower with the `-isa` flag provided, that suggests the culprit is my slow implementation of `reinterpret` and `popcnt`.

**Comment by alexcrichton** [comment]
Ah ok makes sense! 

Looks like the default spec interpreter executes this in 0.8s, and the `-isa` flag runs in 74s

I used this small script to execute the interpreter:

```
expr="(assert_return (invoke \"\""
for i in `seq 0 19`; do
  expr="$expr (f32.const 0)"
done
expr="$expr) (f32.const 0))"
time ./wasm -i $HOME/code/wasmtime/testcase0.wasm -e "$expr"
time ./wasm -isa -i $HOME/code/wasmtime/testcase0.wasm -e "$expr"
```

Also to clarify it's not urgent to fix this, just wanted to log this as the fuzz bug came in

**Comment by conrad-watt** [comment]
Just to flag up - I've identified a fix, but I'm currently dealing with an unrelated deadline, so I'll probably make a PR late next week.

**Comment by conrad-watt** [comment]
With the fix in https://github.com/bytecodealliance/wasmtime/pull/4113, the Isabelle-based interpreter seems to (thankfully!) outperform the base spec interpreter on this example. As I feared, the culprit was `popcnt`'s performance. As I mention in that PR, there are a few more ops which could currently cause similar timeouts if a fuzz test is heavily weighted towards them, so I'll work on fixing those next.

**Comment by alexcrichton** [comment]
Sounds good! I'll ping here if we get a concrete test case but otherwise I'm gonna go ahead and close this since the fuzz bug in question is now fixed.
