### ISSUE TITLE
Implement C/C++ bindings

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#45]
I know of at least one possible user who would like to embed this project in a C program. I've seen in the project's goals that there was an intent to implement the proposed C integration API, so filing an issue to not forget about this.

**Comment by yurydelendik** [comment]
I have some wasm2obj fixes (for my pet project) at #46, though it might provide a workaround for this issue.

**Comment by gkorland** [comment]
Is there a plan to add such binding?

**Comment by alexcrichton** [comment]
Oh this issue is actually slightly out of date! The [proposed C API](https://github.com/WebAssembly/wasm-c-api/tree/8782d5b456f39e5ebf86bbbfa88d0ac13743edfa) is implemented by the [`wasmtime`](https://github.com/bytecodealliance/wasmtime/tree/master/crates/api) crate where building that will generate a dynamic library named `wasmtime` you can link in, so this is done!
