### ISSUE TITLE
cranelift: fma_f32 tests fail on GitHub's `windows-latest` image

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#4512]
I was [testing out](https://github.com/alexcrichton/wasmtime/runs/7473321003?check_suite_focus=true) using the `windows-latest` image with Nick's [stack walking PR](https://github.com/bytecodealliance/wasmtime/pull/4431) because I think that should fix a [longstanding blocker](https://github.com/bytecodealliance/wasmtime/issues/3859) for updating the CI image.

In doing so though I get:

```
FAIL filetests\filetests\runtests\fma.clif: interpret
Caused by:
    Failed test: run: %fma_f32(0x1.060000p7, 0x1.340488p7, 0x1.310e42p4) == 0x1.3b88e6p14, actual: 0x1.3b88e8p14
```

I'm not sure what that corresponds to in [the test itself](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/filetests/filetests/runtests/fma.clif) but I suspect that there's just a difference between the old `fma` symbol on Windows and the new.

cc @afonso360

**Comment by afonso360** [comment]
This is interesting.

I tried to make a [CI run of `fma.clif`](https://github.com/afonso360/wasmtime/actions/runs/2723295231) alone and it did pass the tests. (This is based on the `main` branch from yesterday).


I briefly read the stack walking changes, but I don't see any compile flags or other build changes that would explain this difference.

I pulled your `fast-stack-walking2` branch and [ran it again on CI](https://github.com/afonso360/wasmtime/runs/7480852376?check_suite_focus=true). It fails only on `windows-latest  x86_64-pc-windows-gnu`  but not on `windows-latest`. But I don't understand why it works on `main`, and not with `fast-stack-walking2` applied.


---

Note:

I also had some issues [building the cmake examples on `windows-latest`](https://github.com/afonso360/wasmtime/runs/7480336795?check_suite_focus=true
)
Which don't seem to trigger on the stack walking branch (possibly due to #4369 ?) I haven't investigated this too far.

I can file an issue for this if you think it's relevant.

**Comment by afonso360** [comment]
I suspect this is related to `fma`/`fmaf` bugs on MinGW-w64.

See: https://sourceforge.net/p/mingw-w64/bugs/848/

I compiled the test case in that bug report, with the additional inputs that we are seeing in the interpreter and it also [failed](https://github.com/afonso360/wasmtime/runs/7481751790?check_suite_focus=true#step:10:22).

It does not fail that [test case on `windows-2019`](https://github.com/afonso360/wasmtime/runs/7481751739?check_suite_focus=true#step:10:18), however it fails some others that we don't have in our test suite.

It looks like `fma`/`fmaf` is buggy in MinGW. That bug report has been open for 2 years. What should we do here? I *really* don't want to polyfill fma, should we grab it from some other library?

**Comment by TheGreatRambler** [comment]
> I also had some issues [building the cmake examples on windows-latest](https://github.com/afonso360/wasmtime/runs/7480336795?check_suite_focus=true)
That is because cmake `--target` for tests is not consistent between compilers. `--target test` works for gcc, mingw, macos. `--target RUN_TESTS` works for msvc, really dumb platform difference. It looks like you already know updating should fix it.

**Comment by alexcrichton** [comment]
This has since been resolved so I think this is good to close.
