### ISSUE TITLE
Disable fuzzing by default until the corpus becomes larger?

### ISSUE THREAD

**Issue by joshtriplett** [bytecodealliance/wasmtime#459]
Right now, if I'm understanding the fuzzing infrastructure correctly, `test-all.sh` is building and installing `cargo-fuzz` and the wasmtime `fuzz` project, which combined take a *substantial* amount of compile time, and then using the result to run a fuzz corpus of a single file:

```
     Running `fuzz/target/x86_64-unknown-linux-gnu/debug/compile -artifact_prefix=/home/josh/src/wasmtime/fuzz/artifacts/compile/ ./fuzz/corpus/compile/1340712d77d3db3c79b4b0c1494df18615485480`
INFO: Seed: 2446020617
INFO: Loaded 1 modules   (558450 inline 8-bit counters): 558450 [0x5612cded12a8, 0x5612cdf5981a), 
INFO: Loaded 1 PC tables (558450 PCs): 558450 [0x5612cdf59820,0x5612ce7def40), 
fuzz/target/x86_64-unknown-linux-gnu/debug/compile: Running 1 inputs 1 time(s) each.
Running: ./fuzz/corpus/compile/1340712d77d3db3c79b4b0c1494df18615485480
Executed ./fuzz/corpus/compile/1340712d77d3db3c79b4b0c1494df18615485480 in 0 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

That single file consists of a wasm file containing only the wasm magic and nothing else:

```
$ hd fuzz/corpus/compile/1340712d77d3db3c79b4b0c1494df18615485480 
00000000  00 61 73 6d                                       |.asm|
00000004
```

Integrating fuzzing seems like an excellent idea, but until it has a larger corpus to run, might it make sense to disable it by default and avoid the substantial additional compile time? Folks working on fuzzing could always re-enable it, or run a separate `./fuzz.sh`.

Does that seem reasonable?

**Comment by tschneidereit** [comment]
I agree that this isn't all that useful right now. @fitzgen, what's your take on this?

**Comment by fitzgen** [comment]
I haven't looked at how our CI is set up at all yet, but ideally bounded fuzzing would be a separate job from the unit tests job and those jobs could run in parallel. And for developer experience, we definitely wouldn't want "just running the unit tests locally" to block on building cargo-fuzz and all of cranelift with libfuzzer and all that. 

I think `test-all.sh` is kind of subpar: it is catering towards CI and completeness, rather than developer experience and snappiness, but it is unnecessarily sequential for the CI use case.

So I guess what I am saying is that this is a problem of our toolchain, CI, and testing set up's ergonomics more than about fuzzing in general.

Concretely, where I would like to move towards:

* Break up `test-all.sh` into multiple CI jobs, executed in parallel
    * We don't disable bounded fuzzing in CI, even in its current immature state
* Developers locally do `cargo test -p cranelift-codegen` or `cargo test --all` or `cargo run -- test filetests/wasm` etc...

**Comment by bjorn3** [comment]
> I think test-all.sh is kind of subpar: it is catering towards CI and completeness, rather than developer experience and snappiness, but it is unnecessarily sequential for the CI use case.

That's probably why it is called test-**all**.sh :)

**Comment by alexcrichton** [comment]
I think we've progressed quite a bit since this was first opened and the fuzz corpus is now so large it times out CI if we run all of it, so we run a subset of it :)
