### ISSUE TITLE
Could you please release binaries for all architectures in each release?

### ISSUE THREAD

**Issue by toge** [bytecodealliance/wasmtime#4968]
The 1.0.0 and 1.0.1 releases are for different architectures.

I would like to have the same version for each architecture. 
Is there any plan to release binaries for all architectures in each release?

**Comment by bjorn3** [comment]
An API ratelimit was exceeded during the publish, causing some artifacts to be missing from the release: https://github.com/bytecodealliance/wasmtime/actions/runs/3130842242

**Comment by deadprogram** [comment]
Unfortunately this has resulted in the standard install script being broken on Linux machines.

**Comment by toge** [comment]
@bjorn3 
Thank you for comment.
Will any other binaries be provided for 1.0.1 after the rate limit is removed?

**Comment by alexcrichton** [comment]
Yes this was just an infrastructure hiccup, thanks for the report though! I've almost completed the "surgery" and everything should be there now except for the macOS artifacts which are [tracked here](https://github.com/bytecodealliance/wasmtime/actions/runs/3130842242/jobs/5094674676). I will watch that and make sure it completes, otherwise though I'm going to close this since this should be otherwise fixed.

**Comment by toge** [comment]
@bjorn3 and @alexcrichton 
Thanks a lot!
