### ISSUE TITLE
stack protection

### ISSUE THREAD

**Issue by MarkSwanson** [bytecodealliance/wasmtime#5]
If SIP really does isolate, then perhaps wasm code shouldn't be able to smash the native stack.
Currently Cretonne expects wasm and native code to share the stack so for example wasm code can call an imported native function.

What I'd like:
* SIP wasm environment/code runs using its own stack (sized to fit, mmap guarded).
* ability to switch stacks when making wasm -> native calls, and native->wasm calls.

If imported fn return types are i32, then perhaps this could be marshalled using a register, and a few assembler instructions could take care of the return value and prologue/epilogue modifying the stack pointer.

Is this a crazy idea?

Thanks!

**Comment by sunfishcode** [comment]
This is not crazy :-). Here are a variety of thoughts:

Many native environments already have a guard page on the native stack. If you can determine that the environments you care about already have such a guard page, it may not be necessary to use a separate stack for wasm. That would be a lot simpler than switching stacks at wasm->native or native->wasm calls.

That said, if you're still interested in stack switching, that's something that would have wider applicability as well, as it would have the side benefit of allowing wasm code to be suspended and resumed independently of the main program. 

One issue for either approach is that it's possible for code to allocate stack frames larger than a page, and risk stepping over the guard page without trapping. The latest versions of cretonne-codegen have support for emitting a call to a stack probe function whenever they allocate a stack frame larger than the guard page size. The stack probe function typically works by having a loop that accesses one byte from each page of the newly allocated region, to ensure that it doesn't step over the guard page.

**Comment by MarkSwanson** [comment]
I'm still interested in stack switching.
I'm curious if Cretonne lets us know what CPU registers are dirty at the moment we want to switch - so we just have to save/restore the minimal set of registers? Perhaps the x86_64 SystemV calling conventions help here (because they specify which registers must be preserved?)? 

I would like a separate stack for at least these reasons:
* so wasm code can't mess with the native stack at all. I'm not in a position to trust the wasm code.
* so I can control the max size of the wasm stack (without affecting the max size of the native stack).

The call stack probe functionality seems like it would enable folks to have a controlled and deterministic handling of the situation where the wasm code has run amok and is using too much stack.  Thanks for mentioning it!

**Comment by sunfishcode** [comment]
WebAssembly is designed to allow using the native stack with untrusted code. For example, it's common for web browsers to run completely untrusted wasm on the native stack.

If you just need a stack usage quota, it would be straightforward to make compiled wasm code keep track of it's stack usage, and add quota checks in function prologues. That'd be simpler than stack switching.

That said, for stack switching, the simplest approach would be to create a stub for each exported wasm function and each imported native function, which does the stack switch. wasm->wasm calls could skip the stub. The stub wouldn't have to save and restore registers, other than the stack pointer and possibly the frame pointer. And stubs would work for indirect calls too, without needing to dynamically test whether the callee is wasm or not. The calling convention (system_v etc.) specifies which registers are call-clobbered and may be used as scratch registers in the stub functions.

**Comment by bjfish** [comment]
I am very interested in stack switching (suspending and resuming) which I'd like to use to attempt to create a preemptive wasm runtime. I hope to see more info about stack switching.

**Comment by sunfishcode** [comment]
Cool! I'd be happy to mentor someone with stack switching. I just want to make sure that we think it through, because it is more complex than other options, though it is doable. Here are a few more thoughts:

If you're doing suspending and resuming, do you want to support the ability for wasm to be able to call back out on the native stack? If so, would it be ok if you can't suspend while such a call is in progress?

Do you want to co-exist with native code that may perform stack unwinding, either synchronously (eg. C++ throw) or asynchronously (eg. using libunwind from a signal handler)? If so, it may be possible to register cleanups with the native stack unwinding infrastructure which could unwind the wasm stack when a native unwind reaches the point where a wasm call occurred.

The stub function approach I briefly described above could be implemented as alternate entrypoints, at least on the wasm side. Here's a quick sketch of what this might look like for an exported wasm function:
```asm
foo:
    # save the native SP to a designated location in thread-local storage (TLS)
    ...
    # load the wasm SP from a designated location in TLS
    ...
    # copy any incoming stack arguments from the native stack onto the wasm stack
    ...
__wasm_foo:
    # the regular function body goes here
    ...
```
```asm
    # save the wasm SP to the designated location in TLS
    ...
    # load the native SP from the designated location in TLS
    ...
    ret
```
The `foo` entry point would be callable from native code. It would perform the stack switch and then fall through into the `__wasm_foo` entry. The `__wasm_foo` entry would be callable from wasm code, so wasm->wasm calls wouldn't need to do any extra work.

**Comment by MarkSwanson** [comment]
I primarily want a stack usage quota.
Doing quota checks in function prologues seems like it would satisfy my current requirements.

Atm my plan is to do all async I/O using Rust Generators/Futures/Async/Await in native code. The wasm code would call an imported function like "do_some_io()" and the native futures/async executor would make the necessary calls back into wasm functions as necessary.

So with quota checks and all async I/O done in native code I don't believe suspend/resume buys me anything (for my use case). Also, sharing stacks is helpful because I can share Pinned structs on the stack.

**Comment by bjfish** [comment]
@sunfishcode I would be excited to be mentored on something like this.

Calling the native stack and stack unwinding sound useful for a general purpose implementation. I don't belive my use case described below would require stack unwinding.

My only reference point for designing a preemptive system I've found so far is the Erlang runtime (ERTS) which inspires the following design:

> If you're doing suspending and resuming, do you want to support the ability for wasm to be able to call back out on the native stack? If so, would it be ok if you can't suspend while such a call is in progress?

Maybe, I think the wasm instance would suspend itself, then call a system scheduler function, then later the scheduler would resume the wasm instance later on.  Apart from calling the scheduler, maybe calling imported native functions could work by message passing like ERTS.

> Do you want to co-exist with native code that may perform stack unwinding, either synchronously (eg. C++ throw) or asynchronously (eg. using libunwind from a signal handler)?
I don't think my use case would require this.

**Comment by sunfishcode** [comment]
@MarkSwanson Do you want the quota to be deterministic? Actual frame sizes will vary depending on hardware architecture and cretonne's register allocation choices (which will evolve). If you just want to stop runaway memory usage, this is probably fine. But if you want determinism, another option here would be to define the quota in terms of wasm concepts.

We could define a "frame size" value for a wasm function as a function of its locals, the operand stack at its deepest point, and some fixed quantity to account for per-call stack usage. That would be deterministic, and an approximate upper bound on the actual stack memory usage.

@bjfish Sounds good! It sounds like @MarkSwanson doesn't need stack switching, so would you mind filing a new issue, and giving a brief description of your use case? We can discuss the design of stack switching there. Thanks!

**Comment by MarkSwanson** [comment]
I just want to stop runaway memory usage, so it sounds like a 'frame size' value for wasm functions would work perfectly.

I believe an approximate upper bound could be specified that would be large enough to accommodate different hardware architectures and evolving register allocation choices.

**Comment by sunfishcode** [comment]
Thinking about this more, I think there are other users who would be interested in a "frame size" value for wasm functions, and a quota based on such sizes, so that sounds like a good approach.

Here's an overview of how this might look:
 - cretonne-wasm should compute the frame_size value for a wasm function. To start with, the easiest way would be to just have it compute this value as it decodes. The local variables are decoded in `parse_local_decls`, and the operand stack is tracked within `TranslationState` and its `stack` member. If computing the frame size turns out to add measurable overhead for users that don't need it, but maybe we can find a way to fix that.

 - cretonne-wasm's `FuncEnvironment` trait should allow implementations to perform arbitrary modifications to the function after decoding is finished. It should have an empty default implementation, but users can provide their own implementation (which can insert a quota check at the top of the function, for example).

 - wasmstandalone should have a `GlobalVar` to its `VMContext` to hold the runtime stack usage value, at least when stack quota checking is desired.

 - Then, wasmstandalone can use the new `FuncEnvironment` hook to add code to each function entry block which adds the function's wasm frame size to the current stack usage value, and checks the quota.

**Comment by sunfishcode** [comment]
Yes, all of that sounds right!

**Comment by MarkSwanson** [comment]
Perhaps we could tackle it like this:
* work on getting basic stack switching working
* work on quota check working (wouldn't require stack probes or a guard page right?)

Does that sound alright?

I like your foo: and _wasm_foo: function entry points idea. I don't know Cretonne well enough to know where to get started. Would you mind providing a little more detailed assistance?

Thanks!

**Comment by sunfishcode** [comment]
> work on getting basic stack switching working

I was under the impression that your use case didn't require stack switching, but if you do require it, I'm happy to help you with it.

> work on quota check working (wouldn't require stack probes or a guard page right?)

Yes, if we're enforcing a quota, we can arrange for that to be sufficient, such that we don't need a guard page.

**Comment by MarkSwanson** [comment]
Ah... I've done a couple of design iterations and forgot to update my latest thinking here. 
After reviewing my design again, I have updated it to not require a separate stack.

So stack quota is what I need and would like to help with.

Question: the native Rust stack has a guard page already (iirc). Will this guard page work with the Cretonne stack probe feature? I ask because the stack quota solution has no way of knowing how full the stack is / or what the size of the stack is right? (I wouldn't want the wasm code to segfault...)

I'll start walking the code using your overview above as a guide.

Thanks!

**Comment by sunfishcode** [comment]
> Question: the native Rust stack has a guard page already (iirc). Will this guard page work with the Cretonne stack probe feature? I ask because the stack quota solution has no way of knowing how full the stack is / or what the size of the stack is right? (I wouldn't want the wasm code to segfault...)

Yes, Cretonne's stack probe feature is intended to work in exactly the same way as Rust's existing stack probe feature. I've not yet tested that specifically, but if it somehow doesn't work, I'd consider that a bug.

**Comment by bjorn3** [comment]
triage: I am not sure if this should be closed or not. Stack probes are implemented but using a separate stack for wasm isn't.

**Comment by cfallin** [comment]
Providing an option for stack-switching under wasmtime would be worthwhile; I'm pretty sure @alexcrichton is already thinking about this in the context of async work?

**Comment by alexcrichton** [comment]
Since this was written Wasmtime and cranelift have been updated with multiple strategies for limiting stack usage. Cranelift retains support for Rust-style `__probestack` stack probing but Wasmtime has moved to Cranelift's support for stack quotas. In this mode wasm code can be assigned to consume at most a fixed amount of stack space on the wasm stack. This isn't stack switching, but https://github.com/bytecodealliance/wasmtime/issues/5#issuecomment-391150935 seems to indicate that stack switching wasn't what was desired in the end (this is a 3-year-old issue after all).

On the topic of stack switching the upcoming support for async in Wasmtime does indeed implement this. The purpose for that, though, is suspendable stacks rather than any sort of stack allocation and/or protection. That's all entirely separate from Cranelift, though.

I'm going to go ahead and close this though since I think the spirit of the issue (limiting wasm stack without running the risk of clobbering the native stack too much) is done. If cranelift-supported stack switching is still desired then I think it's probably best if a fresh issue is opened with more specifics targeted at today's state-of-being.
