### ISSUE TITLE
Port the JS WASI polyfill to wasi-common

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#520]
Wasmtime has a JS polyfill implementation of WASI:

https://github.com/CraneStation/wasmtime/tree/polyfill/wasmtime-wasi/js-polyfill

which works by compiling wasmtime's C implementation of WASI with Emscripten, and then adding a bit of support code on top of that.

We should port the support code to work on top of wasi-common, compiled with wasm32-unknown-emscripten. In theory, all the big pieces are in place -- wasi-common provides the same functionality as Wasmtime's C implementation of WASI, Emscripten can provide the same underlying support in both cases, and the support code should roughly be the same. So the work here is in rewiring everything up in [wasi.js](https://github.com/CraneStation/wasmtime/blob/polyfill/wasmtime-wasi/js-polyfill/wasi.js), and porting [polyfill.c](https://github.com/CraneStation/wasmtime/blob/polyfill/wasmtime-wasi/js-polyfill/polyfill.c) to Rust, probably splitting out that `EM_ASM` into a standalone JS file.

I've marked this "help wanted" -- if someone's interested in doing this port, that'd be great (and I can help mentor), but it'd even help just to have more ideas for packaging, binding, or other ways we could make the polyfill better. The current support code and [shell.html](https://github.com/CraneStation/wasmtime/blob/polyfill/wasmtime-wasi/js-polyfill/shell.html) is super minimal.

**Comment by kubkon** [comment]
After putting in some thought into this and doing a little experiment with `nix`, patching up the `nix` crate so that it compiles for the `wasm32-unknown-emscripten` target is not such a trivial task after all as I originally assumed. It is doable, however it will not be immediately testable which IMHO makes this task infinitely more tedious and convoluted than originally planned. Then, even after it is patched, it will probably take some (long?) time for it to make it to a release, and I'd really like to have `wasi-common` compile to Emscripten sooner rather than later.

My proposition here is that we remove `nix` as a dependency altogether and write our own wrappers around the `libc` functions - after all, we've already kinda started giving up on `nix` anyhow when @marmistrz started refactoring `fd_readdir` on Linux and implementing it on Windows. Besides, we don't actually need that much of `nix`'s machinery; we're only ever using a couple of wrappers which should be trivially wrapped by us. I'm happy to do the heavy-lifting here myself, but would appreciate code review and later help in refactoring bits here and there. As an added bonus of this approach, we should be able to wrap up _all_ uses of `libc` functions we currently use in `wasi-common`, making the implementation so much cleaner rather than like now, when some use raw `libc` and some rely on `nix`.

cc @sunfishcode @marmistrz @peterhuene

**Comment by kubkon** [comment]
Actually, I'd appreciate your feedback @alexcrichton on this as well.

**Comment by marmistrz** [comment]
If nix is an obstacle, then I think dropping the dependency on nix is a sound decision, especially that we have a slightly different understanding of `unsafe` than the nix guys.

Could we possibly keep the Rusty wrappers in a separate crate, similar to `winx`, and publish it on crates.io? I propose the name: `younix`!

**Comment by kubkon** [comment]
I agree on keeping the wrappers in a separate crate :-)

**Comment by alexcrichton** [comment]
This sounds like a reasonable solution to me, it's likely inevitable that there's a `sys/*` style hierarchy as libstd has, and emscripten would be "Just Another Platform" that can be targeted.

**Comment by sunfishcode** [comment]
Me too :slightly_smiling_face:

**Comment by kubkon** [comment]
It’s settled then! I’ve already started prepping some ground work and should be able to deliver a working (not necessarily final mind you) solution, i.e., `wasi-common` `nix`-free, soon-ish.

@marmistrz, how about `yanix` for a name? Yet another `nix` crate... 😉

**Comment by marmistrz** [comment]
@kubkon``yanix` is missing the wordplay (and I love wordplays!), but that's fine for me too.

**Comment by sunfishcode** [comment]
Closing this old issue, as the JS polyfill referenced here is no longer in use.
