### ISSUE TITLE
Remove null-check in generated code for `call_indirect` (and `call_ref` soon)

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#5291]
Currently when translating the `call_indirect` instruction Wasmtime will [insert a null-check](https://github.com/bytecodealliance/wasmtime/blob/56daa8a199ab9a79b6404c5a9cd551497594f31b/crates/cranelift/src/func_environ.rs#L1551-L1554) to ensure that we're not calling a null function pointer. Because our representation of a null function pointer is literally a null pointer, however, I think we can actually skip this check entirely due to the [next instruction](https://github.com/bytecodealliance/wasmtime/blob/56daa8a199ab9a79b6404c5a9cd551497594f31b/crates/cranelift/src/func_environ.rs#L1556-L1563) being guaranteed to segfault if it's actually a null pointer.

I don't think this is necessarily as easy as simply removing the null pointer check, however, since I think the `load` needs to at least somehow be annotated with the proper trap code and probably "this can segfault", which I'm not precisely sure how to do. This could be a nice way to clean up the generated code for `call_indirect` slightly thought which is already somewhat large I believe.

**Comment by fitzgen** [comment]
Not sure if we have a bit free in `MemFlags` but if so, we could have a bit that means "the trap code should be indirect-call-to-null-rather-than-heap-out-of-bounds".

**Comment by jameysharp** [comment]
`MemFlags` is a u8 and already has 8 flags defined.

But several flags are mutually exclusive, so we could encode them more concisely. In particular, the `Heap`, `Table`, and `Vmctx` flags represent four states (counting "other") which could be encoded in two bits instead of three.

**Comment by jameysharp** [comment]
At some point we widened `MemFlags` to 16 bits, and in #8134 we added a `MemFlags` bit for indicating another trap-code, so we could do something similar for this case too.

That means there are four cases (can't trap, or could trap with one of three different trap codes). I would kind of like to start packing these enumeration flags into groups of bits, so that this wouldn't change how many bits we're using in `MemFlags`.

It wouldn't be the end of the world to add another bit for this though.
