### ISSUE TITLE
Where is the source about optimization pass ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#5361]
Where is the source about optimization pass ?

Thanks a lot!

**Comment by bjorn3** [comment]
There are optimizations at various places. https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/context.rs lists a couple (DCE, LICM, GVN, preopt, eliminate unreachable code, replace redundant loads) https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/egraph.rs has egraph based optimizations and then every backend individually has peephole optimizations.

**Comment by jameysharp** [comment]
Thanks @bjorn3 for answering this question. I'm going to go ahead and close this issue since there haven't been further questions.

@Zhangyx24, I'd encourage you to come chat with us at https://bytecodealliance.zulipchat.com/#narrow/stream/217117-cranelift if you have any more questions about how we're doing optimization! It's a topic we have too much fun talking about.
