### ISSUE TITLE
Is there an alternative to InstBuilder::fallthrough_return(...)

### ISSUE THREAD

**Issue by ptitSeb** [bytecodealliance/wasmtime#5667]
`InstBuilder::fallthrough_return(...)` as been removed. What could be the alternative to it in current Codegen?

**Comment by bjorn3** [comment]
There isn't. It existed only for the purpose of an integration with Spidermonkey (Baldrdash), which required Spidermonkey to create the function prologue and epilogue. `fallthrough_return` only worked with the Baldrdash calling convention. Baldrdash has since been removed from Spidermonkey and in response the Cranelift side of the integration has been removed too in https://github.com/bytecodealliance/wasmtime/pull/4571.

**Comment by bjorn3** [comment]
Could you tell a bit about the use case you have? Maybe there is an alternative? Or if not this could help with coming up with a design that isn't Spidermonkey specific.

**Comment by ptitSeb** [comment]
I don't think we are actually using this. But `ReturnMode::FallthroughReturn` still exist, so it was in a `match` arm.

**Comment by bjorn3** [comment]
I can't find it anywhere in the Cranelift source.

**Comment by ptitSeb** [comment]
Oh, yeah, you are right, sorry. I mixed up different code origina. I'll close the issue.
