### ISSUE TITLE
hello world from the intro does not compile!!!!

### ISSUE THREAD

**Issue by fgmccabe** [bytecodealliance/wasmtime#6035]
Following the very first section on creating a hello world example.

I used
brew install rust
brew install cargo
rustup target add wasm32-wasi
cargo new hello-world
cargo build --target wasm32-wasi

I get this:

cargo build --target wasm32-wasi

   Compiling hello-rust v0.1.0 (/Users/fgm/Projects/helloworld/hello-rust)
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-wasi` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasi`

error: cannot find macro `println` in this scope
 --> src/main.rs:2:5
  |
2 |     println!("Hello, world!");
  |     ^^^^^^^

error: requires `sized` lang_item

For more information about this error, try `rustc --explain E0463`.
error: could not compile `hello-rust` due to 3 previous errors

Comment: not a good optic when the first example wont compile

**Comment by bjorn3** [comment]
The instructions assume that you installed rustc using rustup rather than an unofficial method like homebrew in your case. I'm not familiar with the homebrew version of rustc, so I don't know how to install the rust standard library for wasm32-wasi using homebrew. If they even compile it for wasm32-wasi at all.

**Comment by saulecabrera** [comment]
As a sanity check: did you remove the rust version installed by homebrew? (`brew rm -f rust`)

**Comment by cfallin** [comment]
@fgmccabe to elaborate a little bit (strictly speaking this is a Rust issue, not a Wasmtime issue, but since we're all here...): the Rust toolchain is most commonly installed via the "rustup" tool, which knows how to download new versions of the toolchain and target SDKs. (That's the `rustup target add...` bit to get `wasm32-wasi`.) However, many package collections and distributions also include custom-packaged snapshots of the individual tools (Rust compiler, Cargo). That's what you got when you did `brew install rust` and `brew install cargo`, and same would be true with e.g. `apt install rust` on a Debian-ish Linux.

I suspect what's happening here is a `$PATH` conflict: your `rustup target add wasm32-wasi` added the `wasm32-wasi` SDK for the Rustup-installed toolchain, but then when you do `cargo build` you invoke your Homebrew-installed toolchain.

Could you:
- Report to us what you see for `which cargo` and `which rustc`;
- If that is *not* `/Users/fgm/.cargo/bin/{cargo,rustc}`, uninstall the brew-installed packages;
- If that also removes rustup itself, either do the `curl | sh` install method (`curl https://sh.rustup.rs | bash`) or look to see if Rustup is in Homebrew's packages;
- Restart your shell to make sure you get env variables fresh from any changes made by the above.

**Comment by fgmccabe** [comment]
I removed the brew version of rust as suggested. 
It now works, thanks

**Comment by fgmccabe** [comment]
Actually, a follow up: it would be good to mention the potential pitfalls in the intro. Installing packages using brew is pretty normal in mac-land

**Comment by cfallin** [comment]
> Actually, a follow up: it would be good to mention the potential pitfalls in the intro. Installing packages using brew is pretty normal in mac-land

Good idea; added in #6036.
