### ISSUE TITLE
cranelift/x64: Use "bit test" instructions

### ISSUE THREAD

**Issue by jameysharp** [bytecodealliance/wasmtime#6103]
#### Feature

x86 has dedicated instructions that we could use for the following patterns:

- `bor` with a constant power-of-two: `bts` ("Bit Test and Set")
- `bxor` with a constant power-of-two: `btc` ("Bit Test and Complement")
- `band` with the bitwise-complement of a constant power-of-two: `btr` ("Bit Test and Reset")
- `icmp` of `band` with a constant power-of-two: `bt` ("Bit Test") (this one may be a little trickier)

It's also possible to match any of these patterns with a non-constant mask produced by `shl 1, x` (plus `bnot` in the case of the `btr` pattern). However in that case it's necessary to make sure that `x` is used modulo `N`, where `N` is the number of bits in the result type. See the lowerings for `shl` for details, and note that the bit-test instructions use their operands modulo the operand width just like the x86 shift instructions do.

#### Benefit

Testing and modifying individual bits is a common pattern in certain kinds of systems programming, so such programs will produce smaller code and may run faster.

These instructions don't modify their operands, unlike the and/or/xor instructions, so they're potentially eligible for load-sinking, and also register allocation may be able to avoid duplicating values. (edit: this is obviously only true for `bt`, not any of the other instructions which do modify their operands.)

#### Implementation

This is mostly like adding any other instruction, but as a particular note, we have an extractor called `imm64_power_of_two` for getting the base-two log of an `iconst` if that constant is a power of two.

**Comment by jameysharp** [comment]
Interesting! I've now checked a few more cases.

- `opt-level` 1-3 all construct the constant mask like you observed, while `opt-level=s` and `opt-level=z` both use these instructions.
- Even with `opt-level=s`, integers smaller than `u64` don't use these instructions.
- The bit index doesn't matter for instruction selection, only for whether a `movl` is sufficient or a full `movq` is required to load the mask into a register. I thought it might prefer these instructions for bits 32-63 since the `movq` encoding is so much larger, but no.
- None of these configurations use the `bt` instruction: apparently `bool` is represented as "anything non-zero is true" so for `x & (1 << 63) != 0` it emitted a single right-shift at all optimization levels.

**Comment by cfallin** [comment]
IMHO we should answer this question based on known performance characteristics of x86 implementations. In modern cores, the bit-test instructions are known to be slower than plain ALU operations. According to [Agner Fog's instruction tables](https://www.agner.org/optimize/instruction_tables.pdf), on IceLake (a recent-ish Intel core) for example, AND/OR/XOR with reg/reg or reg/imm forms have a latency of 1 cycle and a throughput of 4/cycle, while BTS/BTR/BTC with reg/reg or reg/imm have a latency of 1 cycle and a throughput of 2/cycle. It gets worse for memory forms: the implementation is microcoded (11 uops; up to a few uops can be emitted by the hardware decoders, anything greater switches the frontend to microcode-sequencing mode with associated penalty).

In general I think the tendency of modern compilers is to stick to the "RISC-like" areas of x86 because the more complex corners of the ISA are unoptimized; IMHO we should do the same as we'd prefer performance over saving a few bytes of code size.

**Comment by jameysharp** [comment]
Good to know! I'll close this then.
