### ISSUE TITLE
Cryptic error on a `wat` file with floats

### ISSUE THREAD

**Issue by gabriel-fallen** [bytecodealliance/wasmtime#630]
Running `wasmtime --invoke=test wasmtime_bug.wat` produces puzzling error message:
```
Error: failed to process main module `wasmtime_bug.wat`

Caused by:
    0: failed to invoke `test`
    1: unsupported outgoing binding expr As(OutgoingBindingExpressionAs { ty: Scalar(UnrestrictedFloat), idx: 0 })
```

`wasmtime_bug.wat` contains this:
```
(module
  (func $test (result f32)
f32.const 42.0
f32.const 8.0
f32.const 10.0
f32.sub
f32.div
)
  (export "test" (func $test)))
```

`wat2wasm` seems to process this file fine. At least the error message might be more enlightening I think. :)

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to the `wasmtime-interface-types` crate [not having support yet](https://github.com/bytecodealliance/wasmtime/blob/e9622654c58be859153d53b8a8f219e137a58e3e/crates/interface-types/src/lib.rs#L468-L476) for the "unrestricted float" type, but that can actually be trivially fixed by adding a new case there. The interface types support is currently being overhauled, though, so it may be best to wait for the dust to settle a bit.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/bytecodealliance/wasmtime/issues/677 since I think it's unlikely we'll support the old webidl bindings spec for much longer.
