### ISSUE TITLE
Strict lint settings prevent buliding on aarch64

### ISSUE THREAD

**Issue by nomeata** [bytecodealliance/wasmtime#638]
Whlie trying to upgrade the `wasmtime` package in `nixpkgs` (https://github.com/NixOS/nixpkgs/pull/74125) it was pointed out to me that it fails to build on aarch64:

```
   Compiling walrus v0.13.0
error: trivial numeric cast: `u32` as `u32`
   --> crates/wasi-common/src/sys/unix/host_impl.rs:208:19
    |
208 |         st_nlink: filestat.st_nlink as wasi::__wasi_linkcount_t,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> crates/wasi-common/src/lib.rs:3:5
    |
3   |     trivial_numeric_casts,
    |     ^^^^^^^^^^^^^^^^^^^^^
    = help: cast can be replaced by coercion; this might require a temporary variable
error: aborting due to previous error
error: could not compile `wasi-common`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Full log at https://logs.nix.ci/?attempt_id=2f3eab6d-92b7-4a25-af40-3549bc8aad63&key=nixos%2Fnixpkgs.74125

I am no expert, so I don’t even know if wasmtime could even work on that architecture, or if the build problem is with your code or a dependecy, but I hope you’ll tell me.

**Comment by tschneidereit** [comment]
Wasmtime doesn't yet work on AArch64, no. Full Arm support is a high priority, and will happen not too far down the line, but for now it probably doesn't make sense to try to fix these kinds of issues, because the build would fail for other reasons soon after :)

I'll close this issue for now, because we'll want to track Arm-related issues in more direct ways.
