### ISSUE TITLE
Export component::bindgen! macro as a normal function

### ISSUE THREAD

**Issue by kajacx** [bytecodealliance/wasmtime#6690]
#### Export component::bindgen! macro as a normal function

The `wasm_bridge::component::bindgen!` macro works well for it's intended purpose, but I need to modify it's output as a `TokenStream`.

#### Benefit

In [`wasm-bridge`](https://github.com/kajacx/wasm-bridge), I need to call the `wasm_bridge::component::bindgen!` macro and modify the import paths to use `wasm_bridge::` instead of `wasmtime::`, for example.

This can be done by modifying the `TokenStream` (I hope), but I cannot call the macro as a normal function to modify the output. See [this post](https://users.rust-lang.org/t/call-proc-macro-and-modify-its-output/96486) to get a better understanding.

#### Implementation

Proc macro crates cannot export "normal" functions, so I guess the only option would be to split the [`wasmtime_component_macro`](https://docs.rs/wasmtime-component-macro/10.0.1/wasmtime_component_macro/) crate into two crates:

- `wasmtime_component_macro_impl` - Implement the `bindgen` macro as a normal function that takes and returns a `TokenStream`.
- `wasmtime_component_macro` - Export a `bindgen` proc macro, that would just call the impl crate's code.

#### Alternatives

The "use `wasm_bridge::` instead of `wasmtime::` path" issue can be solved by using a `wasmtime` mod like this:
```rust
mod wasmtime {
    pub use wasm_bridge::*;
}
```

but there are other changes to the `TokenStream` that I will need to make.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not sure that this is something we want to "official" support though. Technically it's possible for you to depend on `wasmtime-wit-bindgen` and run that as a code generator, but the output is intertwined with the details of Wasmtime's embedding API which includes some public-but-shouldn't-be-touched portions used by derive (e.g. the hidden methods in `Lift` and `Lower`). While it's possible for you to export all these types in a different crate (such as `wasm_bridge`) there's no stability guarantees or any sort of compatibility guarantees we can reasonably provide. This means that your best bet may be to pin to a specific version of `wasmtime-wit-bindgen` if you'd like to use the source.

Otherwise though the "guts" of `wasmtime-wit-bindgen` are intended to be somewhat simple. The main logic is all in the `wit-parser` crate which takes care of much of the implementation details of WIT and things like that, so you may also want to either copy Wasmtime's implementation and start editing it or start from scratch.

In general though this is not something we can commit on our end to helping to maintain, so in that sense I'm not sure there's going to be a great way for us to satisfy this feature request.

**Comment by alexcrichton** [comment]
Yes I understand invoking the macro doesn't work for you, I mean to depend on the internals of the macro or, as you've put it, copying the `wasmtime_bindgen_macro` crate/module.

Manual updates are expected for something like this as it's not something we can reasonably "officially" support, which is where pinning comes in where you could be compatible with a historical version if you'd like.
