### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Xyncgas** [bytecodealliance/wasmtime#6781]
What's the purpose for webassembly out side of the browser, there's other platform that runs intermediate codes on various platforms already

**Comment by bjorn3** [comment]
Fastly and Cloudflare use Webassembly for computing at the edge to avoid requiring a heavy-weight VM. I believe there are also some npm libraries which wrap a wasm module to avoid having to recompile their C/C++ or Rust code for every architecture and OS.

As for why Webassembly instead of the JVM or .NET. The JVM is not suitable as compilation target for non-Java like languages and requires a GC. And .NET is much more tied to microsoft and only runs on a couple of architectures. Neither is suitable for sandboxing due to their complexity. They both tried and eventually gave up. Webassembly is sandboxed by default.

**Comment by Xyncgas** [comment]
Almost as if it's a tiny container for programs to run with fine controls of permissions and nano-process memory isolation.

I am excited :
Maybe we can rebrand 'webassembly' to 'container', there's nothing wrong to such a generic name
1. Because it's a open project
2. it works
3. Container contains IL ('webassembly'), compilers target container, container running everywhere

Why are we using docker when there is a more efficient container technology which is seemingly what's developed by webassembly

**Comment by bjorn3** [comment]
Fun thing you mention Docker. It's founder once said on twitter: "If WASM+WASI existed in 2008, we would not have needed to create Docker."
