### ISSUE TITLE
WASI: expand networking functions

### ISSUE THREAD

**Issue by npmccallum** [bytecodealliance/wasmtime#70]
We need a full fledged networking API. This includes functions like `socket()`, `connect()`, `bind()`, `listen()`, `accept()`, `getsockopt()`, `setsockopt()`, etc.

**Comment by maxmcd** [comment]
I think this one is pretty well documented: https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-capabilities.md#berkeley-socket-rules

And more from cloudabi on the issue with just providing `socket()`: https://github.com/NuxiNL/cloudabi#capability-based-security

As an example cloudabi uses flower to solve this issue: https://github.com/NuxiNL/flower

**Comment by npmccallum** [comment]
@maxmcd When Red Hat initially evaluated CloudABI, that was one of the primary reasons we rejected it.

**Comment by maxmcd** [comment]
Ah, interesting. Would love to hear more thoughts on why the approach is problematic. Naively it seems elegant enough to hand a program a connection to a db and worry about nothing else.

**Comment by npmccallum** [comment]
@maxmcd It can never work for a self-healing, distributed cluster. It can never work for any kind of proxy except for the most limited one with predefined connections. The list of things it can't do is pretty endless.

CloudABI was an ABI defined for a narrow use case. I'm really hoping WASI isn't.

It is perfectly legitimate for a particular implementation of WASI to return `ENOSYS` on functions like `socket()`. But it is another thing to prevent the working group from standardizing such methods.

**Comment by maxmcd** [comment]
Ah. I asked the proxy question to @EdSchouten recently:

>  I have a quick question. Let's say I have a web server that receives requests and makes arbitrary external network requests, like a web proxy. How would that work with cloudabi? Is it easy to configure flower to allow any external network connections?

> That should be relatively easy. Below is an example of how you can achieve this with the standard Flower command line tools:
>
> 1. Run a switchboard to route requests.
> `$ flower_switchboard ~/flower`
>
> 2. Run an egress process that makes outgoing connections. We could let that hijack the entire address space of the switchboard by using {} as the listen address. Instead, let's only route requests to it that have a 'process' label set to a given value.
> `$ flower_egress_connect ~/flower '{"process": "flower_egress_connect"}'`

> [example of simple network address redacted]

Fair enough though that with access to `socket()` and filtering done by the runtime could provide the same security guarantees.

**Comment by npmccallum** [comment]
@maxmcd Your runtime assumes communication between the host and the WASM code. Ours doesn't. The flower model can work in your use case, but it can't in ours.

**Comment by sunfishcode** [comment]
Yes, networking is a part of the API that we've not done much work on yet. I agree that it's desirable to support more than just preopened sockets from the runtime. I'm optimistic that it'll be feasible to create capabilities that represent address/port/protocol/etc. sets that an application is permitted to create sockets with, however it's obviously going to take work to flesh out all the details.

**Comment by npmccallum** [comment]
@sunfishcode While the BSD socket API isn't great, there are a *lot* of applications and libraries written to it. Whatever we do, we should make sure applications can be trivially compiled for the new APIs.

**Comment by svsintel** [comment]
WASM would make a great Agent based system where messages are passed between agents.  Networking is required for this concept.  I can think of different ugly ways to do the networking.  One way I would like to see an "insecure" versions on sockets, just for concept development. There are two parts to the system, one is the wasm code that would contain network functions. and the vm/engine that would allow/deny socket sysCalls. Only on a system that has both parts could do networking.
A network interface is very important for WASM and WASI

**Comment by jtenner** [comment]
Yeah it's been a couple months since I posted here. What's the status on the working group? I would love to voice my opinion on the current set of suggested ideas.

**Comment by sunfishcode** [comment]
#74 has landed, and we recently published our first API update using the new mechanism and process.

We recently had an [in-person meeting](https://github.com/WebAssembly/WASI/blob/master/meetings/2019/WASI-10-15.md) about HTTP APIs; see the notes there, especially the slides linked there, for more info.

With that said, two things to keep in mind: One is that the next big step in WASI happening soon is that the API will be made modular, so that it's straitghtforward for implementations to chose not to implement features which don't make sense for them. Many implementations won't chose to implement HTTP proxying APIs, for example. The other is that WASI can address multiple levels of abstraction with different APIs. The fact that we're considering an HTTP API now doesn't preclude doing a plain sockets style API as well. And ideally, it should be possible to implement HTTP APIs on top of sockets APIs, so that an implementation could chose to support just sockets, and support the HTTP APIs via a pure wasm module loaded on top.

**Comment by alexhultman** [comment]
HTTP features in a low-level POSIX-like API seems highly out of place - let third-parties implement that stuff on top of the, low-level BSD-like socket syscalls from WASI instead (assuming they are added at some point).

An HTTP server or client is really high-level and can be implemented in a million different ways with tons of different goals and opinions - BSD sockets on the other hand are quite standardized and efficient and a much more logical fit for a low level base WASM API like WASI.

There are about a million web servers and clients ready to compile for WASI as soon as networking syscalls are added - let them figure out how to bring HTTP to WASM.

If you need an HTTP client, wouldn't it makes sense to let the market self-organize and let things like curl or wget come out the victor? I sure would prefer curl-on-WASI, rather than some new HTTP-client from WASI itself.

**Comment by svsintel** [comment]
Once low level sockets are implemented, then any upper level protocol can work.  I can use "fetch" to access external data, but I want sockets to be able to listen.

**Comment by pchickey** [comment]
We agree that low level BSD-like socket functionality should be part of WASI. The HTTP interfaces we are working on are motivated by two environments (Fastly's Compute@Edge product, and Istio/ATS's proxy-wasm environment https://github.com/WebAssembly/wasi-http-proxy) where low-level socket access is inappropriate or impossible. These interfaces are not intended to replace socket interfaces or displace use of curl/wget in those environments.

**Comment by alexhultman** [comment]
> The fact that we're considering an HTTP API now doesn't preclude doing a plain sockets style API as well.

An HTTP API does not preclude a low level API, _but_ whatever magic you decide on for the high level HTTP API _must_ map logically to the low level BSD-socket APIs (coming later on?).

So if you imagine some _magic_ high level fetch-like async HTTP call, then that _magic_ must eventually map down to FDs and pollsets perfectly, otherwise you're going to get a low level platform that does not logically come together with the high level parts, causing havoc and serious incompatibilities within the WASI universe itself.

A web browser running JavaScript has an implicit event-loop that is used to handle Promises, async/await and async fetches, etc. Here it is easy to add new "magic" because you never have to perfectly define the lower level counterparts. So magic stays magic.

Creating an HTTP API before you know exactly how the low level parts should look like is dangerous. What event-loop are you settling for? How should that event-loop map to polling syscalls? How should it integrate with co-routines, etc. If these things don't come together logically at the low level then you're going to end up with two entirely incompatible ways of doing async stuff.

So for instance, we need to be able to get the FD of that HTTP connection and get the FD of the event-loop that you poll with, otherwise we as low level developers cannot seamlessly integrate with high level async networking.

Starting with the low level first, nailing how the universe should work is a lot more sane than first deciding on _magic_ then retrofitting that magic to low level parts.

**Comment by alexhultman** [comment]
Alright I misunderstood what WASI was about. Apparently it's not just low level.

But we still want BSD sockets :)

**Comment by tschneidereit** [comment]
> But we still want BSD sockets :)

As @pchickey said, low level sockets do make sense. I'm not aware of anyone currently driving the process of working out a proposal for a WASI module. If that's something you'd be interested in helping drive, opening an issue in the [WASI spec repository](https://github.com/WebAssembly/WASI/) might make sense. See the recent [issue on WASI-nn](https://github.com/WebAssembly/WASI/issues/272) as an example. (Though of course something not as fully fleshed out definitely works as a starting point!)

We'd be happy to provide help with implementations in Wasmtime, be they experimental to support the standards process, or production-quality to already serve use cases!

**Comment by MikeCamel** [comment]
Suggest adding labels "wasi-network-sockets" and "feature-requests".

**Comment by tschneidereit** [comment]
> Suggest adding labels "wasi-network-sockets" and "feature-requests".

@MikeCamel we don't have those, and should be careful about adding too many labels. I added the [`enhancement`](https://github.com/bytecodealliance/wasmtime/labels/enhancement) label and hope at least for now the combination of that and [`wasi:api`](https://github.com/bytecodealliance/wasmtime/labels/wasi%3Aapi) should be enough. If and when the `wasi` labels become too crowded, we can look into adding a more fine-grained taxonomy.

**Comment by MikeCamel** [comment]
Sounds good, thanks.

**Comment by ShadowJonathan** [comment]
Is there any progress on this front? I was surveying [krustlet](https://github.com/deislabs/krustlet) for usage, but i quickly realized that quite core functionality like networking wasn't implemented all the way back here in `wasmtime`, and by extension, WASI.

Are there any proposals/issues/requests/PRs that I can follow on WASI's side to see progress regarding this?

**Comment by afsec** [comment]
About how BSD sockets capabilites looks like, BASH creates a socket using: `/dev/tcp/www.example.com/80`:
```
exec 3<>/dev/tcp/www.example.com/80
echo -e "GET / HTTP/1.1\r\nhost: http://www.example.com\r\nConnection: close\r\n\r\n" >&3
cat <&3
```
Reference: https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-capabilities.md#berkeley-socket-rules

**Comment by 3miliano** [comment]
We at Kong we are working on full socket implementation for WASI. We included connect, bind, listen, accept, etc. We also added some security features so the host does have some sort of control about what the WASM code can connect to, listen to, and so forth.

I think it aligns with everything I am reading on this thread. 

You can find the proposal here:
https://github.com/Kong/WASI/tree/feat/wasi-sockets
and a potential implementation here:
https://github.com/Kong/wasmtime/tree/feat/wasi-sockets

I would love to hear some feedback on it.

**Comment by ueno** [comment]
@3miliano that looks great! A couple of random comments below:

- IMO it would be nice if TLS and proxies are handled transparently by the host, rather than the Wasm guest, because those involve host dependent network configuration (such as TLS certificates handling and address translation) and may affect portability of Wasm application. If TLS is supported by the host, address resolution would also need to be done by the host, because the original host name is embedded and checked in the handshake (as SNI).
- Support for multiplexing might also be desirable, for protocols like QUIC.

I was sketching a [draft proposal](https://github.com/ueno/wasi-networking) mostly focusing on those aspects, though the other POSIX related stuff is similar to yours.

**Comment by ShadowJonathan** [comment]
@3miliano can we maybe see the link to the pull request into WASI proper once it's up? Interesting proposal, I'll be looking out for it

**Comment by 3miliano** [comment]
@ueno On the topic of TLS. Yes, that would be interesting. One thing to consider is that TLS doesn't exactly require system calls, and therefore you can of course compile a TLS library such as WoflSSL, OpenSSL, etc in WASM itself. Having said that, I hear you about the TLS. That might be something to look out for in the future. 

I'll take a look at your proposal, maybe we can collaborate on a single solution.

**Comment by bjorn3** [comment]
Should this #71 and #73 be moved to https://github.com/webassembly/wasi?

**Comment by cardil** [comment]
The draft of the proposal is here: https://github.com/badeend/WASI-Networking

**Comment by hurae** [comment]
For who concerns, the draft of the proposal now moved to here: https://github.com/WebAssembly/wasi-sockets

**Comment by ondrejtomcik** [comment]
> For who concerns, the draft of the proposal now moved to here: https://github.com/WebAssembly/wasi-sockets

Thanks for keeping us up to date!

**Comment by badeend** [comment]
WASI now has [low-level sockets](https://github.com/WebAssembly/wasi-sockets) and [higher-level HTTP](https://github.com/WebAssembly/wasi-http) support. So I think this can be closed now.
