### ISSUE TITLE
wasmtime on GPU

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasmtime#702]
We should consider to add ability run wasmtime on GPU thought OpenCL or any other language that will be understandable by GPU
In this case we will be able run on GPU any code that is possible to run on CPU using wasmtime ;)

**Comment by sunfishcode** [comment]
Thanks for the report! There are a few different things this might look like:

One would be to just run Wasmtime on a single thread of a GPU. However, individual GPU threads are slow, so that wouldn't be very interesting unless you run many instances of wasmtime in parallel, but then, unless they're all running the same program and probably also operating on the same data, they're likely to create significant branch divergence, so they'll still run slowly. If anyone sees a different way forward for this approach, I'd be very interested to discuss it.

Another would be to create a new language by embedding wasm within a SPMD programming model, similar to what OpenCL does with C. This would be a major research project, including designing a new language, building a toolchain for it, and implementing the engine side of it. If anyone is interested in taking on such a project, I'd be happy to discuss details about what it might look like, and if it makes sense, how we could help. Until a specific plan emerges though, it's not something we're currently expecting to work on.

**Comment by sunfishcode** [comment]
I'm closing this issue, as I don't know of anyone currently planning to take on such a project. But if anyone is interested, feel free to reach out, I'd be interested in hearing what people think could be possible in this space!
