### ISSUE TITLE
Stopping hanging WASM code

### ISSUE THREAD

**Issue by CryZe** [bytecodealliance/wasmtime#712]
I'll be integrating some WASM runtime in my project to let users write plugins for my project. However those plugins may potentially be faulty and hang, so I need some way of interrupting their code execution. One way to go about this that I've seen in other wasm runtimes is via support for metering. You can specify a maximum amount of fuel that code can use for running, and if the fuel is exhausted the execution causes a wasm trap, which then ends up as a Result in Rust. It would be nice to see some kind of support for this use case (if it doesn't already exist in some way).

**Comment by pchickey** [comment]
Over in Lucet, @iximeow was able to find an implementation https://github.com/bytecodealliance/lucet/pull/150 that makes it possible to terminate running Wasm code due to either timeout or other external triggers, but it is pretty specific to the way stack switching to Wasm code works in Lucet.

We'd like to port Lucet's stack management code into Wasmtime as part of merging the Lucet project in, so I'd expect the kill switch mechanism to be ported in as well.

**Comment by alexcrichton** [comment]
I'm gonna try to consolidate these issues and close this in favor of https://github.com/bytecodealliance/wasmtime/issues/860 which I believe is asking for the same feature
