### ISSUE TITLE
wasi-http: does the response-outparam need to allow for an error return?

### ISSUE THREAD

**Issue by elliottt** [bytecodealliance/wasmtime#7276]
We could always set a response that has an appropriate error code and body, why do we allow writing a `result<response, error>`?

**Comment by lukewagner** [comment]
IIUC (not 100% sure here but...), there is a meaningful difference between an error (status) code inside a response (which, I believe is meant to come from the origin) and an error code that you get *instead of* getting a response (which represents an error somewhere along the path).  Symmetrically, this matches the `result<incoming-response, error>` and the `result<future-incoming-response, error>` for `outgoing-handler`.

**Comment by elliottt** [comment]
I think that makes sense: giving the embedder the option ability to respond differently to those errors seems right.
