### ISSUE TITLE
Hashbang support

### ISSUE THREAD

**Issue by Alhadis** [bytecodealliance/wasmtime#740]
It'd be nice if we could invoke WAST files like this:

~~~wast
#!/usr/bin/env wasmtime
(module …)
~~~

Some interpreters of sexp-based languages (SBCL, Emacs, etc) ignore the first line if it's an interpreter directive, even though it isn't valid syntax:

~~~lisp
#!/usr/bin/env sbcl --script
(print "Message")
~~~

~~~elisp
#!/usr/bin/env emacs --batch --script
(message "Hello, world")
~~~

**Comment by sunfishcode** [comment]
This is a fun idea! I'm curious how useful it would be in practice -- in production scenarios, we typically expect people will be using wasm binary files, which are less convenient to handle this way. Would something like https://github.com/bytecodealliance/wasmtime/issues/196 be useful to you?

**Comment by peterhuene** [comment]
I don't think #196 will work for textual format given there's no fixed marker to go off of.

I think the textual format would need support for `#` comments for this to work as desired.

**Comment by Alhadis** [comment]
> Or, alternatively, we could have an text parser extension that ignores a first line starting with `#!`.

That seems like it's the way to go. :+1:

**Comment by sunfishcode** [comment]
I'm still curious how you'd envision this fitting in in practice.

I'd naively expect that any file I'd run often enough to want this kind of convenience should be a binary anyway, in which case a #! in the text format wouldn't help. Do you have other uses in mind?

**Comment by Alhadis** [comment]
@sunfishcode It's mainly about user expectations. Having an interpreter of a text-based format that doesn't understand hashbangs tends to be a downer for UX. You're already giving users the power to run WAST source as binaries, it only feels natural to give it the same/similar treatment as other "interpreted" languages.

It's a nice-to-have, but not something I'd lose sleep over if you decide otherwise.

**Comment by sunfishcode** [comment]
Since this only works for the text format (and the binary format is the primary format that we expect most users will use most of the time), doesn't seem like it would work for Windows, and hard-codes the name of a particular runtime in files (which might be ok for some use cases, but would be awkward in others), my instinct is that we need more motivation before we add new syntax to the text format for this.

**Comment by sunfishcode** [comment]
Anyone wanting to pursue this idea further may also consider bringing this up in the wasm spec repo, which is the authority on the text file syntax -- if the spec repo added any kind of `#!` support to the text syntax, that'd make it straightforward for us to support as well.

That said, raising this in the spec repo would highlight the difficulty such a feature would have in a multiple-implementation ecosystem. `#!` embeds the name of a particular implementation in a file, which doesn't reflect the notion that wasm programs execute against the spec rather than a particular implementation.

**Comment by rene-fonseca** [comment]
It is possible to register the *wat* extension (ie. without relying on a header) with the binfmt feature. But it does seem like text format is more a developer format so not sure if this is something to consider for end users environments. But I have made an example for the binary format - see comment in #196 .

**Comment by peterhuene** [comment]
Nice! I wasn't aware that binfmt also supports file extensions as I've always used it with magic values.

I agree that the text format is geared more towards developers that are experimenting rather than trying to run things in a production environment, so I think it's reasonable to use binfmt to accomplish this.
