### ISSUE TITLE
How to build a wasmtime binary that supports memory64 feature?

### ISSUE THREAD

**Issue by BenSunWhiteBoard** [bytecodealliance/wasmtime#7795]
Hi, I download the release binary, seems it doesn't enable memory64 by default, my running result:

```shell
./wasmtime test.wasm
Error: failed to parse WebAssembly module

Caused by:
        Invalid input WebAssembly code at offset 440: memory64 must be enabled for 64-bit memories
```

I really appreciate it if someone could help me with how to build a wasmtime that could run memory64 wasm file. And if I enable memory64, can I still run memory32 wasm file?

**Comment by bjorn3** [comment]
Try `wasmtime -W memory64=y test.wasm`.

**Comment by alexcrichton** [comment]
Yes memory64 support is not a compile-time feature but a runtime feature, so @bjorn3's suggestion should work, but I'll hold off on closing this until @BenSunWhiteBoard you confirm it works for you

**Comment by alexcrichton** [comment]
memory64 support for wasm is not specified at this time and it's not clear to me that there's an "obvious" design of how to implement it. That PR is one option but isn't necessarily the only one. In that sense it's hard to say what a memory64 wasi would take effort-wise because to me it's not clear to me what the work will be

**Comment by BenSunWhiteBoard** [comment]
Thanks for your kind reply! I have no further questions
