### ISSUE TITLE
How does wasmtime implement memory64 proposal?

### ISSUE THREAD

**Issue by Hellosuna** [bytecodealliance/wasmtime#8010]
hello,I am a newcomer to Rust,it seems that you have finished memory64 proposal in wasmtime,I wonder how it works,I mean what is the main idea,thank you.

**Comment by alexcrichton** [comment]
Hello! Unfortunately this probably won't be the answer your looking for. I can answer direct questions like what the proposal is and how it affects Wasmtime, but I'm not aware of any tutorials or longer-form documentation about how to get started with the proposal. For that you'll be on your own to put the pieces together and figure out if it works for you.

As far as I know the usage of memory64 in Wasmtime and throughout the ecosystem is "not great" at this moment. For example there does not exist any memory64-based WASI target that's usable in standard runtimes, meaning you won't be able to do anything unless you define your own set of host APIs, which is generally a big task.

In terms of the Wasmtime embedding API, not much changed with `memory64`. You still get a [`Memory`](https://docs.rs/wasmtime/latest/wasmtime/struct.Memory.html) and work with that as usual. For wasm this means that WebAssembly can have a memory larger than 4G, and pointers are generally 64-bits instead of 32-bits.

**Comment by alexcrichton** [comment]
I'm going to close this as I think this is answered, but if you have further questions please feel free to continue commenting here or file a new issue.
