### ISSUE TITLE
Inconsistent Wasm validation: InvalidWebAssembly module reject by wasmtime but valid for wasmparser

### ISSUE THREAD

**Issue by pventuzelo** [bytecodealliance/wasmtime#835]
Hi, 

During fuzzing i found the following module that is consider as valid for `wasmparser` but reject by `wasmtime` ( both cranelift & lightbeam backend).

[valid_wasmparser_but_reject_wasmtime.zip](https://github.com/bytecodealliance/wasmtime/files/4077379/valid_wasmparser_but_reject_wasmtime.zip)

Return error by `wasmtime`:
``` sh
$ wasmtime valid_wasmparser_but_reject_wasmtime.wasm 
Error: failed to run main module `valid_wasmparser_but_reject_wasmtime.wasm`

Caused by:
    0: WebAssembly failed to compile
    1: WebAssembly translation error
    2: Invalid input WebAssembly code at offset 518: Invalid var_u7
Error Cranelift: Compile(Wasm(InvalidWebAssembly { message: "Invalid var_u7", offset: 518 }))
```

**Comment by Robbepop** [comment]
`wasm2wat` also has problems with the given `.wasm` file.
Even with `wasm2wat --no-checks` i cannot convert it.

**Comment by alexcrichton** [comment]
It looks like the issue here is that `wasmparser` is skipping (or ignoring errors) in custom sections, but cranelift/lightbeam look to be eagerly reading the section and propagating errors. I've yet to dig much more deeply but I suspect that it's coming from [around here](https://github.com/bytecodealliance/cranelift/blob/b01bee7c5269f72196b42e8bdd874425166bf429/cranelift-wasm/src/module_translator.rs#L85-L90). Something we should likely fix though!

**Comment by yurydelendik** [comment]
Per [WebAssembly spec](https://webassembly.github.io/spec/core/binary/modules.html#binary-customsec) errors in custom sections shall not affect validation of the module. Recommendation if to just ignore any error in custom section (as we do during name section reading).

'reloc.CODE' is documented at https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md and went through multiple iterations/version, so it may not be consistent between toolchains and decoders.

**Comment by yurydelendik** [comment]
Looking at hex dump of the reloc.CODE section (offsets 0x206-222), it looks like the section content is totally messed up and needs to be ignored.

```
000001f8: 80 80 00 0a 72 65 6c 6f  ....relo
00000200: 63 2e 43 4f 44 45 ac ac  c.CODE..
00000208: ac ac ac ac ac ac ac ac  ........
00000210: ac ac ac ac ac ac ac ac  ........
00000218: ac ac ac ac 02 00 00 b5  ........
00000220: 02 01 00 8b 80 80 80 00  ........
00000228: 07 6c 69 6e 6b 69 6e 67  .linking
```

@pventuzelo can tell how this module was create?

The issue is at wasmparser's SectionContent at https://github.com/bytecodealliance/wasmparser/blob/b3f6ed69039372f14ea940216bef43ee8f154f55/src/readers/module.rs#L281 -- we need to ignore invalid custom sections there.

**Comment by pventuzelo** [comment]
Hi @yurydelendik,

The module was created by fuzzing i.e. mutation on existing wasm module.
