### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by geloizi** [bytecodealliance/wasmtime#85]
I've tried several simple cpu bounded benchmarks. It seems that in general wasmtime is twice slower than V8 or Spider Monkey.

**Comment by sunfishcode** [comment]
Wasmtime uses Cranelift, which we know doesn't yet have all the optimization features we're planning for it to have, and we know it's not competitive with browser wasm engines yet. That said, I also do recommend caution when interpreting microbenchmarks.

**Comment by bjorn3** [comment]
This issue is not actionable. In addition a lot has changed since this issue was created, so it may already be fixed.

**Comment by cfallin** [comment]
We've had a number of significant performance improvements since this issue was filed (most notably: new backend, with new register allocator), and while we're still not quite as fast as V8 or SpiderMonkey, we're getting closer. We're hoping to have some continuous performance measurement infrastructure working soon (bytecodealliance/rfcs#3, bytecodealliance/rfcs#4) so we should prefer that for tracking over this general issue, I think.
