### ISSUE TITLE
Will wasmtime support threaded wasm?

### ISSUE THREAD

**Issue by gautammohan** [bytecodealliance/wasmtime#851]
Hi there,

I am a PhD student working on parallelism & concurrency. We are hoping to do some work on parallel wasm, and are looking for a performant nonweb runtime. Are there plans for wasmtime to support the [Threads Proposal](https://github.com/WebAssembly/threads)?

How much work do you think it would be to extend/modify wasmtime to support the semantics proposed by the threads extension? What kind of changes would it entail? If there is interest, I would love to try and contribute.

Thanks in advance!

--Gautam

**Comment by sunfishcode** [comment]
Yes, Wasmtime does plan to implement the threads proposal. The major things that need to be done are:
 - Add atomics support to Cranelift: https://github.com/bytecodealliance/cranelift/issues/582
 - Since the wasm threads proposal doesn't include a way to create threads, design an threading API that a runtime can expose (something similar to `pthread_create`, `pthread_join`, etc.) and implement it in Wasmtime
 - Port a pthread library to WASI libc, using this API and the wasm atomics, possibly starting from musl's pthread support
 - Make sure Wasmtime's `Instance` , `LinearMemory`, and other data structures are thread safe.

**Comment by alexcrichton** [comment]
Looks like we have a few of these issues open in the issue tracker so I'm going to close this in favor of a dedicated tracking issue -- https://github.com/bytecodealliance/wasmtime/issues/888
