### ISSUE TITLE
Dead link in WASI tutorial

### ISSUE THREAD

**Issue by zslayton** [bytecodealliance/wasmtime#9107]
Hi! The WASI tutorial contains a dead link to the browser polyfill:

https://github.com/bytecodealliance/wasmtime/blob/22a4480e90d2e5bb4933a0bd027bd31d007b8b04/docs/WASI-tutorial.md?plain=1#L323

**Comment by surban** [comment]
This is essential. Without the polyfill I don't see any possibility to run WebAssembly in the browser.

**Comment by sunfishcode** [comment]
Thanks for the report! I've now filed https://github.com/bytecodealliance/wasmtime/pull/9471 to update Wasmtime's WASI documentation.

The old browser polyfill was very limited and hard to use, and has since been surpassed by better alternatives, in particular, [Jco](https://github.com/bytecodealliance/jco) provides a toolchain for running Wasm programs in browsers, that includes WASI support.
