### ISSUE TITLE
GitHub release uploads fail intermittently, breaking the install script

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#978]
Our GitHub actions push workflow uploads binaries to a GitHub release—`dev` for `master`, or the last published tag for tagged releases. This upload [fails intermittently](https://github.com/bytecodealliance/wasmtime/runs/466063744?check_suite_focus=true#step:20:1), which in turn breaks our install script.

We should see if there's something to be done about these failures on our end, or do something to mitigate them. One option might be to retry the upload at least a couple of times, if it's just flaky.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Ok the plot is unfortunately thickening. 

After #982 uploading an asset is now done entirely in a loop. The [publish logs though](https://github.com/bytecodealliance/wasmtime/runs/468642071) sure enough failed again. The retry did indeed work. The first error we got was `Error saving asset` but every error after that was `Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}` which sort of sonds like it was already uploaded. Checking the releases page, however, it definitely wasn't uploaded.

No idea what's happening here, so time to get more coarse. https://github.com/bytecodealliance/wasmtime/pull/989 is an attempt to just retry the entire upload process.

**Comment by alexcrichton** [comment]
Ok looks like that did the trick, the build at https://github.com/bytecodealliance/wasmtime/runs/470965512?check_suite_focus=true failed, then retried automatically, and succeeded on the retry. We now currently have a full suite of builds. 

I need to do one more fix for our tagged releases since they'll be retried as well, then I think we should be good to close this.
