### ISSUE TITLE
Permanent build warnings about `Failed to run rustfmt on ISLE-generated code`

### ISSUE THREAD

**Issue by SingleAccretion** [bytecodealliance/wasmtime#9899]
I am sure everyone building wasmtime is familiar with:
```
warning: cranelift-codegen@0.116.0: Failed to run `rustfmt` on ISLE-generated code: Custom { kind: Other, error: "`rustfmt` exited with status exit code: 0xc00000fd" }
```
It is a constant feature of the CI builds as well. `0xc00000fd` is `STATUS_STACK_OVERFLOW`.

**Comment by alexcrichton** [comment]
I've seen a similar error in CI quite a lot but I always figured it was because `rustfmt` wasn't installed and that error wasn't otherwise specifically handled. Otherwise though:

> I am sure everyone building wasmtime is familiar with:

I never actually saw this day-to-day myself and I think it's a Windows-specific issue where Windows has smaller thread stacks by default than other platforms (or at least I think, maybe I'm wrong...). 

Mostly just wanted to highlight that you might be one of the first developers to frequently work on Wasmtime on Windows, so please keep your eyes peeled for any other gotchas and points of friction. Most of the preexisting maintainers I believe don't develop day-to-day on Windows, so I wouldn't be surprised if this weren't the only point of friction. #9901 is much appreciated (as is all your DWARF work, thank you!) and please feel free to call out any other issues you see!
