### ISSUE TITLE
Null-terminator asymmetry in trap message APIs

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#994]
*wasm_trap_message* adds an extra null-terminator. Is this intended?

*wasm_trap_new* already requires buffer to be null-terminated.

https://github.com/bytecodealliance/wasmtime/blob/master/crates/c-api/src/lib.rs#L1026-L1048

```rust
pub unsafe extern "C" fn wasm_trap_message(trap: *const wasm_trap_t, out: *mut wasm_message_t) {
    let mut buffer = Vec::new();
    buffer.extend_from_slice((*trap).trap.borrow().message().as_bytes());
    buffer.reserve_exact(1);
    buffer.push(0); // extra null terminator
    (*out).set_buffer(buffer);
}
```

Normally I consume strings with the buffer size returned (dont care about the actual bytes). But I would need to trim extra chars (ie. null-terminator) if this is allowed to be appended. But annoying to manage in particular if a message/buffer at some point can get manipulated recursively.

**Comment by peterhuene** [comment]
I recently fixed `wasm_trap_new` to remove the null terminator from the string being stored internally since we didn't need it, so this should be putting it back on when giving the message back to C without a duplicate null.

Despite the fact that the byte length is given back with `wasm_message_t`, [this comment](https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h#L372) in the C API proposal indicates that the message always needs a null terminator.

**Comment by rene-fonseca** [comment]
Ok, thanks. That would do it.
I do switch between the different releases but didnt look for new behvaior on this.

**Comment by peterhuene** [comment]
@rene-fonseca thanks for bringing this to our attention though! The C API is pretty important to us for enabling embedding from many different languages, so if there is anything you find that's not what you expect or is behaving badly, we'll try to get addressed.  Can this issue now be closed?

**Comment by rene-fonseca** [comment]
Closed - I can follow up if I there is anything left when testing on latest release.
